import { makeStyles, mergeClasses, tokens } from '@fluentui/react-components';
import { layout } from './theme.js';

const media = Object.freeze({
  narrow: `@media (max-width: ${layout.breakpoints.medium - 1}px)`,
  lifecycle: `@media (min-width: ${layout.breakpoints.lifecycle}px)`,
  phases: `@media (min-width: ${layout.breakpoints.phases}px)`,
  facts: `@media (min-width: ${layout.breakpoints.facts}px)`,
  medium: `@media (min-width: ${layout.breakpoints.medium}px)`,
  mediumOnly: `@media (min-width: ${layout.breakpoints.medium}px) and (max-width: ${layout.breakpoints.wide - 1}px)`,
  wide: `@media (min-width: ${layout.breakpoints.wide}px)`,
  tall: `@media (min-height: ${layout.breakpoints.tall}px)`,
});

export const useCanvasStyles = makeStyles({
  app: {
    minWidth: 0,
    minHeight: '100dvh',
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground1,
  },
  shell: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
    minHeight: '100dvh',
  },
  visuallyHidden: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    whiteSpace: 'nowrap',
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
  },
  commandBar: {
    position: 'sticky',
    top: 0,
    zIndex: 20,
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: tokens.spacingHorizontalM,
    minWidth: 0,
    minHeight: layout.commandBar,
    boxSizing: 'border-box',
    paddingInline: tokens.spacingHorizontalM,
    paddingBlock: tokens.spacingVerticalXS,
    backgroundColor: tokens.colorNeutralBackground2,
    borderBottomStyle: 'solid',
    borderBottomWidth: tokens.strokeWidthThin,
    borderBottomColor: tokens.colorNeutralStroke2,
    [media.lifecycle]: {
      flexWrap: 'nowrap',
    },
  },
  brand: {
    display: 'inline-flex',
    alignItems: 'baseline',
    gap: tokens.spacingHorizontalXS,
    flexShrink: 0,
    margin: 0,
    fontWeight: tokens.fontWeightSemibold,
  },
  brandMark: {
    alignSelf: 'center',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: tokens.spacingHorizontalL,
    height: tokens.spacingVerticalL,
    color: tokens.colorBrandForeground1,
    borderRadius: tokens.borderRadiusSmall,
  },
  brandSub: {
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightRegular,
  },
  commandRule: {
    alignSelf: 'stretch',
    width: tokens.strokeWidthThin,
    backgroundColor: tokens.colorNeutralStroke2,
  },
  context: {
    position: 'relative',
    display: 'flex',
    flex: `1 1 ${layout.contextBasis}`,
    minWidth: 0,
    maxWidth: layout.contextMax,
  },
  contextIdentity: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    minWidth: 0,
    minHeight: layout.commandControl,
    boxSizing: 'border-box',
    paddingInline: tokens.spacingHorizontalS,
    paddingBlock: tokens.spacingVerticalXXS,
    borderRadius: tokens.borderRadiusMedium,
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopWidth: tokens.strokeWidthThin,
    borderRightWidth: tokens.strokeWidthThin,
    borderBottomWidth: tokens.strokeWidthThin,
    borderLeftWidth: tokens.strokeWidthThin,
    borderTopColor: tokens.colorNeutralStrokeAccessible,
    borderRightColor: tokens.colorNeutralStrokeAccessible,
    borderBottomColor: tokens.colorNeutralStrokeAccessible,
    borderLeftColor: tokens.colorNeutralStrokeAccessible,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  contextText: {
    display: 'grid',
    minWidth: 0,
    textAlign: 'left',
  },
  contextCaption: {
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase100,
    lineHeight: tokens.lineHeightBase100,
    fontWeight: tokens.fontWeightSemibold,
    textTransform: 'uppercase',
    letterSpacing: tokens.spacingHorizontalXXS,
  },
  contextName: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: tokens.fontSizeBase200,
    lineHeight: tokens.lineHeightBase200,
    fontWeight: tokens.fontWeightSemibold,
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    marginLeft: 'auto',
    flexShrink: 0,
  },
  refreshButton: {
    '&[aria-disabled="true"]': {
      color: tokens.colorNeutralForeground2,
      backgroundColor: tokens.colorNeutralBackground1Pressed,
      borderTopColor: tokens.colorNeutralStrokeAccessible,
      borderRightColor: tokens.colorNeutralStrokeAccessible,
      borderBottomColor: tokens.colorNeutralStrokeAccessible,
      borderLeftColor: tokens.colorNeutralStrokeAccessible,
      cursor: 'progress',
    },
  },
  icon: {
    display: 'inline-block',
    flexShrink: 0,
    width: tokens.spacingHorizontalL,
    height: tokens.spacingVerticalL,
  },
  smallIcon: {
    display: 'inline-block',
    flexShrink: 0,
    width: tokens.spacingHorizontalM,
    height: tokens.spacingVerticalM,
  },
  shellBody: {
    display: 'grid',
    flex: '1 1 auto',
    gridTemplateColumns: 'minmax(0, 1fr)',
    gridTemplateAreas: '"rail" "work" "dock"',
    gridTemplateRows: 'auto auto minmax(0, 1fr)',
    minWidth: 0,
    [media.mediumOnly]: {
      gridTemplateColumns: `${layout.activityRail} minmax(0, 1fr)`,
      gridTemplateAreas: '"rail work" "rail dock"',
      gridTemplateRows: 'auto minmax(0, 1fr)',
    },
    [media.wide]: {
      gridTemplateColumns: `${layout.activityRail} minmax(${layout.workMin}, 1fr) minmax(${layout.detailsDockMin}, ${layout.detailsDockMax})`,
      gridTemplateAreas: '"rail work dock"',
      gridTemplateRows: 'minmax(0, 1fr)',
    },
  },
  rail: {
    gridArea: 'rail',
    display: 'flex',
    alignItems: 'center',
    paddingBlock: tokens.spacingVerticalS,
    paddingInline: tokens.spacingHorizontalM,
    backgroundColor: tokens.colorNeutralBackground2,
    borderBottomStyle: 'solid',
    borderBottomWidth: tokens.strokeWidthThin,
    borderBottomColor: tokens.colorNeutralStroke2,
    [media.medium]: {
      flexDirection: 'column',
      alignItems: 'center',
      borderBottomWidth: 0,
      borderRightStyle: 'solid',
      borderRightWidth: tokens.strokeWidthThin,
      borderRightColor: tokens.colorNeutralStroke2,
      paddingInline: tokens.spacingHorizontalS,
    },
  },
  railList: {
    display: 'flex',
    gap: tokens.spacingHorizontalXS,
    minWidth: 0,
    margin: 0,
    padding: 0,
    listStyleType: 'none',
    [media.medium]: {
      flexDirection: 'column',
    },
  },
  railItem: {
    position: 'relative',
    display: 'flex',
  },
  railButton: {
    minWidth: layout.commandControl,
    width: layout.commandControl,
    height: layout.commandControl,
    padding: 0,
  },
  railCurrent: {
    color: tokens.colorBrandForeground1,
    borderTopColor: tokens.colorCompoundBrandStroke,
    borderRightColor: tokens.colorCompoundBrandStroke,
    borderBottomColor: tokens.colorCompoundBrandStroke,
    borderLeftColor: tokens.colorCompoundBrandStroke,
    boxShadow: `inset 0 calc(-1 * ${tokens.strokeWidthThicker}) 0 ${tokens.colorCompoundBrandStroke}`,
    [media.medium]: {
      boxShadow: `inset ${tokens.strokeWidthThicker} 0 0 ${tokens.colorCompoundBrandStroke}`,
    },
  },
  railButtonLater: {
    borderTopStyle: 'dashed',
    borderRightStyle: 'dashed',
    borderBottomStyle: 'dashed',
    borderLeftStyle: 'dashed',
    borderTopColor: tokens.colorNeutralStrokeDisabled,
    borderRightColor: tokens.colorNeutralStrokeDisabled,
    borderBottomColor: tokens.colorNeutralStrokeDisabled,
    borderLeftColor: tokens.colorNeutralStrokeDisabled,
  },
  railLater: {
    position: 'absolute',
    right: `calc(-1 * ${tokens.spacingHorizontalXXS})`,
    bottom: `calc(-1 * ${tokens.spacingVerticalXXS})`,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: tokens.spacingHorizontalM,
    height: tokens.spacingVerticalM,
    color: tokens.colorNeutralForegroundDisabled,
    backgroundColor: tokens.colorNeutralBackground2,
    borderRadius: tokens.borderRadiusCircular,
    fontSize: tokens.fontSizeBase100,
  },
  work: {
    gridArea: 'work',
    minWidth: 0,
    backgroundColor: tokens.colorNeutralBackground3,
  },
  workBody: {
    display: 'grid',
    alignContent: 'start',
    minWidth: 0,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  workStrip: {
    minWidth: 0,
    paddingBlock: tokens.spacingVerticalXS,
    paddingInline: tokens.spacingHorizontalL,
    borderBottomStyle: 'solid',
    borderBottomWidth: tokens.strokeWidthThin,
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  breadcrumb: {
    minWidth: 0,
    overflow: 'hidden',
  },
  breadcrumbText: {
    display: 'block',
    minWidth: 0,
    overflowWrap: 'anywhere',
  },
  identity: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    minWidth: 0,
    paddingBlock: tokens.spacingVerticalS,
    paddingInline: tokens.spacingHorizontalL,
    borderBottomStyle: 'solid',
    borderBottomWidth: tokens.strokeWidthThin,
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  identityTitle: {
    minWidth: 0,
    margin: 0,
    overflowWrap: 'anywhere',
    '&:focus': {
      outlineColor: tokens.colorStrokeFocus2,
      outlineOffset: tokens.spacingHorizontalXXS,
      outlineStyle: 'solid',
      outlineWidth: tokens.strokeWidthThick,
    },
  },
  identityKey: {
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase200,
    overflowWrap: 'anywhere',
  },
  identityNote: {
    flexBasis: '100%',
    maxWidth: layout.proseMeasure,
    margin: 0,
    color: tokens.colorNeutralForeground2,
  },
  region: {
    minWidth: 0,
    paddingBlock: tokens.spacingVerticalM,
    paddingInline: tokens.spacingHorizontalL,
    borderBottomStyle: 'solid',
    borderBottomWidth: tokens.strokeWidthThin,
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  sectionHead: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: tokens.spacingHorizontalS,
    marginBottom: tokens.spacingVerticalS,
  },
  sectionTitle: {
    margin: 0,
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase200,
    lineHeight: tokens.lineHeightBase200,
    fontWeight: tokens.fontWeightSemibold,
    textTransform: 'uppercase',
    letterSpacing: tokens.spacingHorizontalXXS,
  },
  caption: {
    maxWidth: layout.proseMeasure,
    margin: 0,
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase200,
    lineHeight: tokens.lineHeightBase200,
    overflowWrap: 'anywhere',
  },
  focalCard: {
    display: 'grid',
    gap: tokens.spacingVerticalS,
    minWidth: 0,
    paddingBlock: tokens.spacingVerticalM,
    paddingInline: tokens.spacingHorizontalL,
    borderLeftStyle: 'solid',
    borderLeftWidth: tokens.strokeWidthThicker,
    borderLeftColor: tokens.colorCompoundBrandStroke,
    boxShadow: tokens.shadow4,
  },
  focalUnavailable: {
    borderLeftColor: tokens.colorNeutralStrokeAccessible,
    boxShadow: 'none',
  },
  focalComplete: {
    borderLeftColor: tokens.colorPaletteGreenBorder2,
  },
  eyebrow: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXS,
    margin: 0,
    color: tokens.colorBrandForeground1,
    fontSize: tokens.fontSizeBase200,
    lineHeight: tokens.lineHeightBase200,
    fontWeight: tokens.fontWeightSemibold,
    textTransform: 'uppercase',
    letterSpacing: tokens.spacingHorizontalXXS,
  },
  eyebrowUnavailable: {
    color: tokens.colorNeutralForeground3,
  },
  eyebrowComplete: {
    color: tokens.colorPaletteGreenForeground1,
  },
  focalHeadline: {
    maxWidth: layout.headlineMeasure,
    margin: 0,
    overflowWrap: 'anywhere',
  },
  focalCondensedCue: {
    maxWidth: layout.proseMeasure,
    margin: 0,
    color: tokens.colorNeutralForeground3,
    overflowWrap: 'anywhere',
  },
  focalDetail: {
    maxWidth: layout.proseMeasure,
    margin: 0,
    overflowWrap: 'anywhere',
  },
  focalFacts: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr)',
    gap: tokens.spacingVerticalS,
    [media.facts]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
      columnGap: tokens.spacingHorizontalXXL,
    },
  },
  fact: {
    display: 'grid',
    gap: tokens.spacingVerticalXXS,
    minWidth: 0,
  },
  factLabel: {
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase100,
    lineHeight: tokens.lineHeightBase100,
    fontWeight: tokens.fontWeightSemibold,
    textTransform: 'uppercase',
    letterSpacing: tokens.spacingHorizontalXXS,
  },
  factValue: {
    maxWidth: layout.proseMeasure,
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase200,
    lineHeight: tokens.lineHeightBase200,
    overflowWrap: 'anywhere',
  },
  instructionLead: {
    maxWidth: layout.proseMeasure,
    margin: 0,
    color: tokens.colorNeutralForeground2,
    overflowWrap: 'anywhere',
  },
  instructionSteps: {
    display: 'grid',
    gap: tokens.spacingVerticalXS,
    maxWidth: layout.proseMeasure,
    marginBlock: tokens.spacingVerticalM,
    marginInline: 0,
    paddingLeft: tokens.spacingHorizontalXXL,
    color: tokens.colorNeutralForeground2,
  },
  instructionFacts: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr)',
    gap: tokens.spacingVerticalS,
    paddingTop: tokens.spacingVerticalM,
    borderTopStyle: 'solid',
    borderTopWidth: tokens.strokeWidthThin,
    borderTopColor: tokens.colorNeutralStroke2,
    [media.facts]: {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
      columnGap: tokens.spacingHorizontalXXL,
    },
  },
  lifecycleList: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr)',
    gap: tokens.spacingVerticalS,
    margin: 0,
    padding: 0,
    listStyleType: 'none',
    [media.lifecycle]: {
      gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
      columnGap: tokens.spacingHorizontalS,
    },
  },
  lifecycleItem: {
    position: 'relative',
    display: 'grid',
    gridTemplateColumns: `${tokens.spacingHorizontalXL} minmax(0, 1fr)`,
    gap: tokens.spacingHorizontalS,
    minWidth: 0,
    [media.lifecycle]: {
      gridTemplateColumns: 'minmax(0, 1fr)',
      rowGap: tokens.spacingVerticalXS,
    },
  },
  stepMarker: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: tokens.spacingHorizontalXL,
    height: tokens.spacingVerticalXL,
    boxSizing: 'border-box',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopWidth: tokens.strokeWidthThin,
    borderRightWidth: tokens.strokeWidthThin,
    borderBottomWidth: tokens.strokeWidthThin,
    borderLeftWidth: tokens.strokeWidthThin,
    borderTopColor: tokens.colorNeutralStrokeAccessible,
    borderRightColor: tokens.colorNeutralStrokeAccessible,
    borderBottomColor: tokens.colorNeutralStrokeAccessible,
    borderLeftColor: tokens.colorNeutralStrokeAccessible,
    borderRadius: tokens.borderRadiusCircular,
    color: tokens.colorNeutralForeground3,
    backgroundColor: tokens.colorNeutralBackground1,
    fontSize: tokens.fontSizeBase100,
    fontWeight: tokens.fontWeightSemibold,
  },
  stepComplete: {
    color: tokens.colorNeutralForegroundOnBrand,
    backgroundColor: tokens.colorPaletteGreenBackground3,
    borderTopColor: tokens.colorPaletteGreenBackground3,
    borderRightColor: tokens.colorPaletteGreenBackground3,
    borderBottomColor: tokens.colorPaletteGreenBackground3,
    borderLeftColor: tokens.colorPaletteGreenBackground3,
  },
  stepCurrent: {
    color: tokens.colorNeutralForegroundOnBrand,
    backgroundColor: tokens.colorBrandBackground,
    borderTopColor: tokens.colorCompoundBrandStroke,
    borderRightColor: tokens.colorCompoundBrandStroke,
    borderBottomColor: tokens.colorCompoundBrandStroke,
    borderLeftColor: tokens.colorCompoundBrandStroke,
  },
  stepUnknown: {
    borderTopStyle: 'dashed',
    borderRightStyle: 'dashed',
    borderBottomStyle: 'dashed',
    borderLeftStyle: 'dashed',
    backgroundColor: tokens.colorNeutralBackground2,
  },
  stepText: {
    minWidth: 0,
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase200,
    lineHeight: tokens.lineHeightBase200,
  },
  stepTextCurrent: {
    color: tokens.colorNeutralForeground1,
    fontWeight: tokens.fontWeightSemibold,
  },
  stepState: {
    display: 'block',
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase100,
    lineHeight: tokens.lineHeightBase100,
  },
  progress: {
    display: 'grid',
    gap: tokens.spacingVerticalS,
    marginTop: tokens.spacingVerticalM,
    paddingTop: tokens.spacingVerticalS,
    borderTopStyle: 'solid',
    borderTopWidth: tokens.strokeWidthThin,
    borderTopColor: tokens.colorNeutralStroke2,
  },
  progressTrack: {
    display: 'flex',
    gap: tokens.spacingHorizontalXXS,
    minWidth: 0,
    height: tokens.strokeWidthThickest,
    overflow: 'hidden',
    borderRadius: tokens.borderRadiusCircular,
  },
  progressSegment: {
    minWidth: tokens.spacingHorizontalXXS,
    flexBasis: 0,
    borderRadius: tokens.borderRadiusCircular,
  },
  segmentDone: {
    backgroundColor: tokens.colorPaletteGreenBorder2,
  },
  segmentDoing: {
    backgroundColor: tokens.colorBrandBackground,
  },
  segmentBlocked: {
    backgroundColor: tokens.colorPaletteRedBorder2,
  },
  segmentOpen: {
    backgroundColor: tokens.colorNeutralStroke1,
  },
  legend: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: `${tokens.spacingVerticalXS} ${tokens.spacingHorizontalM}`,
    margin: 0,
    padding: 0,
    listStyleType: 'none',
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase200,
  },
  legendItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXS,
  },
  legendCount: {
    color: tokens.colorNeutralForeground1,
    fontWeight: tokens.fontWeightSemibold,
  },
  phaseList: {
    display: 'grid',
    margin: 0,
    padding: 0,
    listStyleType: 'none',
    borderTopStyle: 'solid',
    borderTopWidth: tokens.strokeWidthThin,
    borderTopColor: tokens.colorNeutralStroke2,
  },
  phaseRow: {
    display: 'grid',
    gridTemplateColumns: `${tokens.spacingHorizontalXL} minmax(0, 1fr)`,
    gap: `${tokens.spacingVerticalXS} ${tokens.spacingHorizontalM}`,
    minWidth: 0,
    paddingBlock: tokens.spacingVerticalMNudge,
    paddingInline: tokens.spacingHorizontalS,
    borderBottomStyle: 'solid',
    borderBottomWidth: tokens.strokeWidthThin,
    borderBottomColor: tokens.colorNeutralStroke2,
    [media.phases]: {
      gridTemplateColumns: `${tokens.spacingHorizontalXL} minmax(0, 1fr) minmax(${layout.phaseDistribution}, 1fr) auto`,
      alignItems: 'center',
      columnGap: tokens.spacingHorizontalL,
    },
  },
  phaseCurrent: {
    backgroundColor: tokens.colorNeutralBackground2,
    boxShadow: `inset ${tokens.strokeWidthThicker} 0 0 ${tokens.colorCompoundBrandStroke}`,
  },
  phaseMark: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: tokens.spacingHorizontalXL,
    height: tokens.spacingVerticalXL,
    boxSizing: 'border-box',
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopWidth: tokens.strokeWidthThin,
    borderRightWidth: tokens.strokeWidthThin,
    borderBottomWidth: tokens.strokeWidthThin,
    borderLeftWidth: tokens.strokeWidthThin,
    borderTopColor: tokens.colorNeutralStrokeAccessible,
    borderRightColor: tokens.colorNeutralStrokeAccessible,
    borderBottomColor: tokens.colorNeutralStrokeAccessible,
    borderLeftColor: tokens.colorNeutralStrokeAccessible,
    borderRadius: tokens.borderRadiusCircular,
  },
  phaseName: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    minWidth: 0,
    margin: 0,
    overflowWrap: 'anywhere',
  },
  phaseDistribution: {
    gridColumn: 2,
    display: 'flex',
    gap: tokens.spacingHorizontalXXS,
    width: '100%',
    maxWidth: layout.phaseDistribution,
    height: tokens.strokeWidthThickest,
    overflow: 'hidden',
    borderRadius: tokens.borderRadiusCircular,
    [media.phases]: {
      gridColumn: 3,
    },
  },
  phaseCount: {
    gridColumn: 2,
    margin: 0,
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase200,
    lineHeight: tokens.lineHeightBase200,
    [media.phases]: {
      gridColumn: 4,
      textAlign: 'right',
    },
  },
  unavailableRegion: {
    display: 'grid',
    gridTemplateColumns: `${tokens.spacingHorizontalXL} minmax(0, 1fr)`,
    gap: tokens.spacingHorizontalM,
    paddingBlock: tokens.spacingVerticalM,
    paddingInline: tokens.spacingHorizontalL,
    borderTopStyle: 'dashed',
    borderRightStyle: 'dashed',
    borderBottomStyle: 'dashed',
    borderLeftStyle: 'dashed',
    borderTopWidth: tokens.strokeWidthThin,
    borderRightWidth: tokens.strokeWidthThin,
    borderBottomWidth: tokens.strokeWidthThin,
    borderLeftWidth: tokens.strokeWidthThin,
    borderTopColor: tokens.colorNeutralStrokeAccessible,
    borderRightColor: tokens.colorNeutralStrokeAccessible,
    borderBottomColor: tokens.colorNeutralStrokeAccessible,
    borderLeftColor: tokens.colorNeutralStrokeAccessible,
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground2,
    color: tokens.colorNeutralForeground2,
  },
  trail: {
    display: 'grid',
    margin: 0,
    padding: 0,
    listStyleType: 'none',
  },
  trailItem: {
    position: 'relative',
    display: 'grid',
    gridTemplateColumns: `${tokens.spacingHorizontalL} minmax(0, 1fr)`,
    gap: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalM}`,
    minWidth: 0,
    paddingBottom: tokens.spacingVerticalL,
    ':not(:last-child)::after': {
      content: '""',
      position: 'absolute',
      top: tokens.spacingVerticalM,
      bottom: 0,
      left: tokens.spacingHorizontalS,
      width: tokens.strokeWidthThick,
      backgroundColor: tokens.colorNeutralStroke2,
    },
    [media.tall]: {
      paddingBottom: tokens.spacingVerticalXL,
    },
  },
  trailNode: {
    position: 'relative',
    zIndex: 1,
    gridRowStart: 1,
    gridRowEnd: 3,
    justifySelf: 'center',
    width: tokens.spacingHorizontalS,
    height: tokens.spacingVerticalS,
    boxSizing: 'border-box',
    marginTop: tokens.spacingVerticalXS,
    borderTopStyle: 'solid',
    borderRightStyle: 'solid',
    borderBottomStyle: 'solid',
    borderLeftStyle: 'solid',
    borderTopWidth: tokens.strokeWidthThick,
    borderRightWidth: tokens.strokeWidthThick,
    borderBottomWidth: tokens.strokeWidthThick,
    borderLeftWidth: tokens.strokeWidthThick,
    borderTopColor: tokens.colorNeutralStrokeAccessible,
    borderRightColor: tokens.colorNeutralStrokeAccessible,
    borderBottomColor: tokens.colorNeutralStrokeAccessible,
    borderLeftColor: tokens.colorNeutralStrokeAccessible,
    borderRadius: tokens.borderRadiusCircular,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  trailNodeCurrent: {
    borderTopColor: tokens.colorCompoundBrandStroke,
    borderRightColor: tokens.colorCompoundBrandStroke,
    borderBottomColor: tokens.colorCompoundBrandStroke,
    borderLeftColor: tokens.colorCompoundBrandStroke,
    backgroundColor: tokens.colorCompoundBrandStroke,
  },
  trailDate: {
    margin: 0,
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase100,
    lineHeight: tokens.lineHeightBase100,
    fontWeight: tokens.fontWeightSemibold,
    textTransform: 'uppercase',
  },
  trailText: {
    maxWidth: layout.proseMeasure,
    margin: 0,
    overflowWrap: 'anywhere',
  },
  chooser: {
    position: 'relative',
    width: '100%',
    minWidth: 0,
  },
  contextField: {
    position: 'relative',
    width: '100%',
    minWidth: 0,
    gridTemplateColumns: 'auto minmax(0, 1fr)',
    alignItems: 'center',
    '& .fui-Field__label': {
      marginRight: tokens.spacingHorizontalS,
      paddingBlock: 0,
      color: tokens.colorNeutralForeground3,
      fontSize: tokens.fontSizeBase100,
      lineHeight: tokens.lineHeightBase100,
      fontWeight: tokens.fontWeightSemibold,
      textTransform: 'uppercase',
      letterSpacing: tokens.spacingHorizontalXXS,
      [media.narrow]: {
        position: 'absolute',
        width: '1px',
        height: '1px',
        margin: '-1px',
        padding: 0,
        overflow: 'hidden',
        clip: 'rect(0, 0, 0, 0)',
        whiteSpace: 'nowrap',
        borderTopWidth: 0,
        borderRightWidth: 0,
        borderBottomWidth: 0,
        borderLeftWidth: 0,
      },
    },
  },
  chooserControl: {
    gridColumnStart: 2,
    gridColumnEnd: 3,
    width: '100%',
    minWidth: 0,
    borderTopColor: tokens.colorNeutralStrokeAccessible,
    borderRightColor: tokens.colorNeutralStrokeAccessible,
    borderBottomColor: tokens.colorNeutralStrokeAccessible,
    borderLeftColor: tokens.colorNeutralStrokeAccessible,
    '&:has(input:focus-visible)': {
      outlineColor: tokens.colorStrokeFocus2,
      outlineOffset: tokens.spacingHorizontalXXS,
      outlineStyle: 'solid',
      outlineWidth: tokens.strokeWidthThick,
    },
    '&[aria-disabled="true"]': {
      color: tokens.colorNeutralForeground2,
      backgroundColor: tokens.colorNeutralBackground1Pressed,
      borderTopColor: tokens.colorNeutralStrokeAccessible,
      borderRightColor: tokens.colorNeutralStrokeAccessible,
      borderBottomColor: tokens.colorNeutralStrokeAccessible,
      borderLeftColor: tokens.colorNeutralStrokeAccessible,
      cursor: 'progress',
    },
    '&[aria-disabled="true"] input': {
      color: tokens.colorNeutralForeground2,
      cursor: 'progress',
    },
    '&[aria-disabled="true"] .fui-Combobox__expandIcon': {
      color: tokens.colorNeutralForeground2,
      cursor: 'progress',
    },
  },
  chooserSummaryBand: {
    position: 'absolute',
    zIndex: 2,
    gridColumnStart: 2,
    gridColumnEnd: 3,
    top: '100%',
    left: 0,
    right: 0,
    height: layout.chooserSummary,
    boxSizing: 'border-box',
    marginTop: 0,
    paddingBlock: tokens.spacingVerticalXXS,
    paddingInline: tokens.spacingHorizontalS,
    overflow: 'hidden',
    color: tokens.colorNeutralForeground2,
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopLeftRadius: tokens.borderRadiusMedium,
    borderTopRightRadius: tokens.borderRadiusMedium,
    borderTopStyle: 'solid',
    borderTopWidth: tokens.strokeWidthThin,
    borderLeftStyle: 'solid',
    borderLeftWidth: tokens.strokeWidthThin,
    borderRightStyle: 'solid',
    borderRightWidth: tokens.strokeWidthThin,
    borderBottomStyle: 'none',
    borderBottomWidth: 0,
    borderTopColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
    borderRightColor: tokens.colorNeutralStroke2,
    boxShadow: tokens.shadow16,
  },
  chooserListbox: {
    boxSizing: 'border-box',
    maxHeight: `calc(${layout.chooserRow} * 5) !important`,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    padding: 0,
    rowGap: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderTopStyle: 'none',
    borderTopWidth: 0,
    borderRightStyle: 'solid',
    borderRightWidth: tokens.strokeWidthThin,
    borderBottomStyle: 'solid',
    borderBottomWidth: tokens.strokeWidthThin,
    borderLeftStyle: 'solid',
    borderLeftWidth: tokens.strokeWidthThin,
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
    [media.tall]: {
      maxHeight: `calc(${layout.chooserRow} * 8) !important`,
    },
  },
  chooserOption: {
    boxSizing: 'border-box',
    height: layout.chooserRow,
    minHeight: layout.chooserRow,
    paddingBlock: tokens.spacingVerticalS,
    paddingInline: tokens.spacingHorizontalS,
    '&[aria-selected="true"]': {
      backgroundColor: tokens.colorNeutralBackground1Selected,
    },
    '&[aria-selected="true"] .fui-Option__checkIcon': {
      color: tokens.colorBrandForeground1,
    },
    '&[data-activedescendant-focusvisible]': {
      backgroundColor: tokens.colorNeutralBackground2,
      boxShadow: `inset ${tokens.strokeWidthThicker} 0 0 ${tokens.colorCompoundBrandStroke}`,
    },
    '&[aria-selected="true"][data-activedescendant-focusvisible]': {
      backgroundColor: tokens.colorNeutralBackground1Selected,
    },
    '&[data-activedescendant-focusvisible]::after': {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
  },
  chooserOptionText: {
    display: 'block',
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  chooserSummary: {
    display: 'block',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  chooserEmpty: {
    position: 'absolute',
    zIndex: 2,
    gridColumnStart: 2,
    gridColumnEnd: 3,
    top: `calc(100% + ${layout.chooserSummary})`,
    left: 0,
    width: '100%',
    boxSizing: 'border-box',
    margin: 0,
    paddingBlock: tokens.spacingVerticalS,
    paddingInline: tokens.spacingHorizontalS,
    color: tokens.colorNeutralForeground2,
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: tokens.borderRadiusMedium,
    borderBottomRightRadius: tokens.borderRadiusMedium,
    borderTopStyle: 'none',
    borderTopWidth: 0,
    borderRightStyle: 'solid',
    borderRightWidth: tokens.strokeWidthThin,
    borderBottomStyle: 'solid',
    borderBottomWidth: tokens.strokeWidthThin,
    borderLeftStyle: 'solid',
    borderLeftWidth: tokens.strokeWidthThin,
    borderRightColor: tokens.colorNeutralStroke2,
    borderBottomColor: tokens.colorNeutralStroke2,
    borderLeftColor: tokens.colorNeutralStroke2,
    boxShadow: tokens.shadow16,
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
  },
  dock: {
    gridArea: 'dock',
    minWidth: 0,
    backgroundColor: tokens.colorNeutralBackground2,
    borderTopStyle: 'solid',
    borderTopWidth: tokens.strokeWidthThin,
    borderTopColor: tokens.colorNeutralStroke2,
    [media.wide]: {
      borderTopWidth: 0,
      borderLeftStyle: 'solid',
      borderLeftWidth: tokens.strokeWidthThin,
      borderLeftColor: tokens.colorNeutralStroke2,
    },
  },
  dockBody: {
    display: 'grid',
    gridTemplateColumns: `repeat(auto-fit, minmax(min(${layout.dockTileMin}, 100%), 1fr))`,
    alignItems: 'start',
    gap: `${tokens.spacingVerticalNone} ${tokens.spacingHorizontalXXL}`,
    minWidth: 0,
    paddingInline: tokens.spacingHorizontalM,
    paddingBottom: tokens.spacingVerticalM,
    [media.wide]: {
      gridTemplateColumns: 'minmax(0, 1fr)',
      paddingBottom: tokens.spacingVerticalXXL,
    },
  },
  dockSection: {
    minWidth: 0,
    paddingBlock: tokens.spacingVerticalM,
    borderBottomStyle: 'solid',
    borderBottomWidth: tokens.strokeWidthThin,
    borderBottomColor: tokens.colorNeutralStroke2,
  },
  messageStack: {
    display: 'grid',
    gap: tokens.spacingVerticalS,
    marginTop: tokens.spacingVerticalS,
  },
  statusSummary: {
    display: 'flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXS,
    margin: 0,
    overflowWrap: 'anywhere',
  },
  properties: {
    display: 'grid',
    gridTemplateColumns: `minmax(0, ${layout.propertyLabel}) minmax(0, 1fr)`,
    gap: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    marginBlock: tokens.spacingVerticalS,
    marginInline: 0,
    '& dt': {
      color: tokens.colorNeutralForeground3,
      fontSize: tokens.fontSizeBase200,
    },
    '& dd': {
      minWidth: 0,
      margin: 0,
      overflowWrap: 'anywhere',
    },
  },
  surfaces: {
    display: 'grid',
    gap: tokens.spacingVerticalS,
    marginBlock: tokens.spacingVerticalS,
    marginInline: 0,
    padding: 0,
    listStyleType: 'none',
  },
  surface: {
    display: 'grid',
    gridTemplateColumns: `${tokens.spacingHorizontalL} minmax(0, 1fr) auto`,
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    color: tokens.colorNeutralForeground4,
  },
  surfaceOpen: {
    color: tokens.colorNeutralForeground1,
    fontWeight: tokens.fontWeightSemibold,
  },
  surfaceWhen: {
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightRegular,
  },
  accordionPanel: {
    paddingInline: tokens.spacingHorizontalS,
  },
  sourceList: {
    display: 'grid',
    gap: tokens.spacingVerticalXS,
    margin: 0,
    paddingBlock: tokens.spacingVerticalS,
    '& dt': {
      color: tokens.colorNeutralForeground3,
      fontSize: tokens.fontSizeBase100,
      fontWeight: tokens.fontWeightSemibold,
      textTransform: 'uppercase',
    },
    '& dd': {
      minWidth: 0,
      margin: 0,
      marginBottom: tokens.spacingVerticalS,
      overflowWrap: 'anywhere',
      fontSize: tokens.fontSizeBase200,
    },
  },
  sourceCode: {
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase100,
  },
  statusBar: {
    position: 'static',
    zIndex: 15,
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalM}`,
    minWidth: 0,
    minHeight: layout.statusBar,
    boxSizing: 'border-box',
    paddingBlock: tokens.spacingVerticalXS,
    paddingInline: tokens.spacingHorizontalM,
    color: tokens.colorNeutralForeground2,
    backgroundColor: tokens.colorNeutralBackground4,
    borderTopStyle: 'solid',
    borderTopWidth: tokens.strokeWidthThin,
    borderTopColor: tokens.colorNeutralStroke2,
    fontSize: tokens.fontSizeBase200,
    lineHeight: tokens.lineHeightBase200,
    [media.medium]: {
      position: 'sticky',
      bottom: 0,
    },
  },
  statusSegment: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: tokens.spacingHorizontalXS,
    minWidth: 0,
    overflowWrap: 'anywhere',
  },
  statusStrong: {
    color: tokens.colorNeutralForeground1,
    fontWeight: tokens.fontWeightSemibold,
  },
  statusKeyboard: {
    display: 'none',
    '& kbd': {
      paddingInline: tokens.spacingHorizontalXS,
      color: tokens.colorNeutralForeground2,
      backgroundColor: tokens.colorNeutralBackground1,
      borderTopStyle: 'solid',
      borderRightStyle: 'solid',
      borderBottomStyle: 'solid',
      borderLeftStyle: 'solid',
      borderTopWidth: tokens.strokeWidthThin,
      borderRightWidth: tokens.strokeWidthThin,
      borderBottomWidth: tokens.strokeWidthThin,
      borderLeftWidth: tokens.strokeWidthThin,
      borderTopColor: tokens.colorNeutralStroke1,
      borderRightColor: tokens.colorNeutralStroke1,
      borderBottomColor: tokens.colorNeutralStroke1,
      borderLeftColor: tokens.colorNeutralStroke1,
      borderRadius: tokens.borderRadiusSmall,
      fontFamily: tokens.fontFamilyBase,
      fontSize: tokens.fontSizeBase100,
      lineHeight: tokens.lineHeightBase100,
    },
    [media.medium]: {
      display: 'inline-flex',
    },
  },
  statusPush: {
    [media.medium]: {
      marginLeft: 'auto',
    },
  },
});

export { mergeClasses };
