// @ts-check
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { inventoryDigest } from '../dude-engine/lib/profile.mjs';

const SCRIPT = fileURLToPath(new URL('./lint.mjs', import.meta.url));

/** @returns {string} */
function rootWithManifest() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'dude-lint-layout-'));
  fs.mkdirSync(path.join(root, '.dude/ideas'), { recursive: true });
  write(
    root,
    '.dude/metadata/bundle-manifest.md',
    '# Bundle Manifest\n\n```json\n{"source_repo":"x","source_ref":"main","installed_ref":"main"}\n```\n',
  );
  write(root, '.dude/metadata/profile.md', profileDocument({ enabled_packs: [], installed: {} }));
  return root;
}

/** @param {Record<string, unknown>} payload @returns {string} */
function profileDocument(payload) {
  return `# Install Profile\n\n\`\`\`json\n${JSON.stringify(payload, null, 2)}\n\`\`\`\n`;
}

/** @returns {Record<string, unknown>} */
function completeCurrentProfile() {
  const artifactPath = '.github/prompts/dude-pack-demo-review.prompt.md';
  const inventory = {
    version: 1,
    pack: 'demo',
    source: { type: 'library', location: '/catalog', ref: 'main' },
    manifest_sha256: '1'.repeat(64),
    artifacts: [{
      path: artifactPath,
      kind: 'prompts',
      source: 'prompts/dude-pack-demo-review.prompt.md',
      source_sha256: '2'.repeat(64),
      installed_sha256: '3'.repeat(64),
    }],
    digest: '',
  };
  inventory.digest = inventoryDigest(inventory);
  return {
    enabled_packs: ['demo'],
    installed: {
      demo: {
        files: [artifactPath],
        installed_at: '2026-07-13T00:00:00.000Z',
        inventory,
      },
    },
  };
}

/** @param {string} root @param {string} relPath @param {string} content */
function write(root, relPath, content) {
  const absolutePath = path.join(root, relPath);
  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  fs.writeFileSync(absolutePath, content);
}

/** @param {string} root */
function lint(root) {
  const result = spawnSync(process.execPath, [SCRIPT, root], { encoding: 'utf8' });
  return { code: result.status, output: `${result.stdout || ''}${result.stderr || ''}` };
}

/**
 * @param {{ status?: string, specPath?: string, intakeHeading?: string }} [options]
 * @returns {string}
 */
function ledger(options = {}) {
  const status = options.status || 'draft';
  const specPath = options.specPath || '';
  const intakeHeading = options.intakeHeading || 'Idea';
  return [
    '---',
    `status: ${status}`,
    `spec_path: ${specPath}`,
    '---',
    '',
    `## ${intakeHeading}`,
    '',
    'Intake body.',
    '',
    '## Coordinator Log',
    '',
  ].join('\n');
}

/** @param {string} root @param {string} idea @param {string} feature */
function writeDefinedIdea(root, idea, feature) {
  const specPath = `.dude/specs/${feature}/spec.md`;
  write(root, specPath, `# Spec: ${feature}\n`);
  write(root, `.dude/ideas/${idea}.md`, ledger({ status: 'defined', specPath }));
}

const TASK_BOARD_START = '<!-- dude:board:start -->';
const TASK_BOARD_NOTICE =
  '<!-- generated by @dude — do not hand-edit; regenerated on every status/define refresh -->';
const TASK_BOARD_END = '<!-- dude:board:end -->';
const TASK_CANONICAL_NOTICE =
  '<!-- canonical task units — edit task descriptions here, but let @dude mutate state glyphs -->';

/** @param {string} idea @returns {string} */
function ideaAudit(idea) {
  return `<!-- audit log: .dude/ideas/${idea}.md#coordinator-log -->`;
}

/**
 * @param {string} audit
 * @param {{ rendered?: boolean, body?: string }} [options]
 * @returns {string}
 */
function taskDocument(audit, options = {}) {
  const body = options.body || '';
  if (!options.rendered) return `${audit}${body ? `\n${body}` : ''}\n`;
  return [
    TASK_BOARD_START,
    TASK_BOARD_NOTICE,
    '### Ready Now',
    TASK_BOARD_END,
    TASK_CANONICAL_NOTICE,
    audit,
    body,
    '',
  ].filter((line, index, lines) => line || index === lines.length - 1).join('\n');
}

test('lint accepts canonical draft and defined ideas and reports idea counts', () => {
  const root = rootWithManifest();
  try {
    write(root, '.dude/specs/x/spec.md', '# Spec\n');
    write(
      root,
      '.dude/ideas/draft.md',
      '---\nstatus: draft\nspec_path:\n---\n\n## Idea\n\nDraft.\n\n## Coordinator Log\n',
    );
    write(
      root,
      '.dude/ideas/x.md',
      '---\nstatus: defined\nspec_path: .dude/specs/x/spec.md\n---\n\n## Idea\n\nDefined.\n\n## Coordinator Log\n',
    );
    write(root, '.dude/state/task-state.json', '{".dude/specs/x/tasks.md":{"glyphs":{},"updated_at":"2026-01-01T00:00:00.000Z"}}\n');
    const result = lint(root);
    assert.equal(result.code, 0, result.output);
    assert.match(result.output, /Scanned: 2 idea\(s\)/);
    assert.match(result.output, /0 warning\(s\), 0 failure\(s\)/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint accepts quoted canonical scalars and CRLF frontmatter consistently', () => {
  const root = rootWithManifest();
  try {
    write(root, '.dude/specs/x/spec.md', '# Spec\r\n');
    write(
      root,
      '.dude/ideas/x.md',
      '---\r\nstatus: "defined"\r\nspec_path: \'.dude/specs/x/spec.md\'\r\n---\r\n\r\n## Idea\r\n\r\nQuoted.\r\n\r\n## Coordinator Log\r\n',
    );

    const result = lint(root);

    assert.equal(result.code, 0, result.output);
    assert.match(result.output, /Scanned: 1 idea\(s\)/);
    assert.match(result.output, /0 warning\(s\), 0 failure\(s\)/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint rejects invalid status and malformed or duplicate idea frontmatter', () => {
  const invalidStatusRoot = rootWithManifest();
  const duplicateRoot = rootWithManifest();
  const danglingRoot = rootWithManifest();
  try {
    write(
      invalidStatusRoot,
      '.dude/ideas/x.md',
      '---\nstatus: ready\nspec_path:\n---\n\n## Idea\n\nInvalid.\n\n## Coordinator Log\n',
    );
    const invalidStatus = lint(invalidStatusRoot);
    assert.equal(invalidStatus.code, 1, invalidStatus.output);
    assert.match(invalidStatus.output, /invalid status 'ready' \(valid: draft, defined\)/);

    write(duplicateRoot, '.dude/specs/x/spec.md', '# Spec\n');
    write(
      duplicateRoot,
      '.dude/ideas/x.md',
      '---\nstatus: defined\nspec_path: .dude/specs/x/spec.md\nspec_path: .dude/specs/x/spec.md\n---\n\n## Idea\n\nDuplicate.\n\n## Coordinator Log\n',
    );
    const duplicate = lint(duplicateRoot);
    assert.equal(duplicate.code, 1, duplicate.output);
    assert.match(duplicate.output, /duplicate frontmatter key 'spec_path'/);

    write(
      danglingRoot,
      '.dude/ideas/x.md',
      '---\nstatus: defined\nspec_path: .dude/specs/x/spec.md\n\n## Idea\n\nDangling.\n\n## Coordinator Log\n',
    );
    const dangling = lint(danglingRoot);
    assert.equal(dangling.code, 1, dangling.output);
    assert.match(dangling.output, /frontmatter closing delimiter/);
  } finally {
    fs.rmSync(invalidStatusRoot, { recursive: true, force: true });
    fs.rmSync(duplicateRoot, { recursive: true, force: true });
    fs.rmSync(danglingRoot, { recursive: true, force: true });
  }
});

test('lint rejects Windows-style traversal in canonical spec identity', () => {
  const root = rootWithManifest();
  try {
    write(
      root,
      '.dude/ideas/x.md',
      '---\nstatus: defined\nspec_path: .dude/specs/..\\outside/spec.md\n---\n\n## Idea\n\nUnsafe.\n\n## Coordinator Log\n',
    );
    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /spec_path.*must point at/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint strictly rejects missing delimiters and malformed quoted idea frontmatter', () => {
  const cases = [
    {
      name: 'missing opening delimiter',
      content: 'status: draft\nspec_path:\n---\n\n## Idea\n\nBody.\n\n## Coordinator Log\n',
      expected: /frontmatter opening delimiter is missing or malformed/,
    },
    {
      name: 'missing closing delimiter',
      content: '---\nstatus: draft\nspec_path:\n\n## Idea\n\nBody.\n\n## Coordinator Log\n',
      expected: /frontmatter closing delimiter is missing or malformed/,
    },
    {
      name: 'malformed quoted scalar',
      content: '---\nstatus: "draft\nspec_path:\n---\n\n## Idea\n\nBody.\n\n## Coordinator Log\n',
      expected: /frontmatter key 'status' has a malformed quoted scalar/,
    },
  ];

  for (const fixture of cases) {
    const root = rootWithManifest();
    try {
      write(root, '.dude/ideas/x.md', fixture.content);
      const result = lint(root);
      assert.equal(result.code, 1, `${fixture.name}\n${result.output}`);
      assert.match(result.output, fixture.expected, fixture.name);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  }
});

test('lint rejects dangling, non-file, and symbolic-link canonical spec targets', { skip: process.platform === 'win32' }, () => {
  const danglingRoot = rootWithManifest();
  const directoryRoot = rootWithManifest();
  const symlinkRoot = rootWithManifest();
  const outside = fs.mkdtempSync(path.join(os.tmpdir(), 'dude-lint-outside-'));
  try {
    write(
      danglingRoot,
      '.dude/ideas/x.md',
      ledger({ status: 'defined', specPath: '.dude/specs/x/spec.md' }),
    );
    const dangling = lint(danglingRoot);
    assert.equal(dangling.code, 1, dangling.output);
    assert.match(dangling.output, /spec identity target does not exist/);

    fs.mkdirSync(path.join(directoryRoot, '.dude/specs/x/spec.md'), { recursive: true });
    write(
      directoryRoot,
      '.dude/ideas/x.md',
      ledger({ status: 'defined', specPath: '.dude/specs/x/spec.md' }),
    );
    const directory = lint(directoryRoot);
    assert.equal(directory.code, 1, directory.output);
    assert.match(directory.output, /spec identity target is not a regular file/);

    write(outside, 'spec.md', '# Outside\n');
    fs.mkdirSync(path.join(symlinkRoot, '.dude/specs/x'), { recursive: true });
    fs.symlinkSync(path.join(outside, 'spec.md'), path.join(symlinkRoot, '.dude/specs/x/spec.md'));
    write(
      symlinkRoot,
      '.dude/ideas/x.md',
      ledger({ status: 'defined', specPath: '.dude/specs/x/spec.md' }),
    );
    const symlink = lint(symlinkRoot);
    assert.equal(symlink.code, 1, symlink.output);
    assert.match(symlink.output, /spec identity contains symbolic link/);
  } finally {
    fs.rmSync(danglingRoot, { recursive: true, force: true });
    fs.rmSync(directoryRoot, { recursive: true, force: true });
    fs.rmSync(symlinkRoot, { recursive: true, force: true });
    fs.rmSync(outside, { recursive: true, force: true });
  }
});

test('lint rejects malformed non-empty canonical draft spec_path values', () => {
  const cases = [
    { name: 'Windows traversal', specPath: '.dude/specs/..\\outside/spec.md' },
    { name: 'arbitrary path', specPath: 'nope' },
  ];
  const results = [];

  for (const fixture of cases) {
    const root = rootWithManifest();
    try {
      write(root, '.dude/ideas/x.md', ledger({ status: 'draft', specPath: fixture.specPath }));
      results.push({ ...fixture, ...lint(root) });
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  }

  assert.deepEqual(
    results.map((result) => result.code),
    [1, 1],
    results.map((result) => `${result.name}:\n${result.output}`).join('\n'),
  );
  for (const result of results) {
    assert.match(result.output, /\.dude\/ideas\/x\.md/, result.name);
    assert.ok(result.output.includes(`spec_path '${result.specPath}'`), result.output);
    assert.match(result.output, /spec_path.*must point at \.dude\/specs\/<feature>\/spec\.md/, result.name);
  }
});

test('lint validates canonical draft spec_path targets without granting ownership', () => {
  const missingRoot = rootWithManifest();
  const existingRoot = rootWithManifest();
  const packageRoot = rootWithManifest();
  const specPath = '.dude/specs/x/spec.md';
  try {
    write(missingRoot, '.dude/ideas/x.md', ledger({ status: 'draft', specPath }));

    write(existingRoot, specPath, '# Spec\n');
    write(existingRoot, '.dude/ideas/x.md', ledger({ status: 'draft', specPath }));

    write(packageRoot, specPath, '# Spec\n');
    write(packageRoot, '.dude/ideas/x.md', ledger({ status: 'draft', specPath }));
    write(packageRoot, '.dude/specs/x/tasks.md', taskDocument(ideaAudit('x')));

    const missing = lint(missingRoot);
    const existing = lint(existingRoot);
    const taskPackage = lint(packageRoot);

    // FR-029 (T034): a draft ledger must not carry a resolvable spec_path. The
    // inventory now emits FEATURE_DRAFT_SPEC_PATH and lint fails instead of
    // tolerating a draft whose canonical spec_path target already exists.
    assert.equal(existing.code, 1, existing.output);
    assert.match(existing.output, /\.dude\/ideas\/x\.md.*\[FEATURE_DRAFT_SPEC_PATH\]/);

    assert.equal(taskPackage.code, 1, taskPackage.output);
    assert.match(taskPackage.output, /package \.dude\/specs\/x\/spec\.md has no defined idea owner/);
    assert.match(taskPackage.output, /breadcrumb target \.dude\/ideas\/x\.md/);

    assert.equal(missing.code, 1, missing.output);
    assert.match(missing.output, /\.dude\/ideas\/x\.md.*spec_path '\.dude\/specs\/x\/spec\.md'/);
    assert.match(missing.output, /unsafe or unresolved.*spec identity target does not exist/);
  } finally {
    fs.rmSync(missingRoot, { recursive: true, force: true });
    fs.rmSync(existingRoot, { recursive: true, force: true });
    fs.rmSync(packageRoot, { recursive: true, force: true });
  }
});

test('lint accepts an empty draft spec_path in a canonical idea', () => {
  const root = rootWithManifest();
  try {
    write(root, '.dude/ideas/x.md', ledger({ status: 'draft' }));

    const result = lint(root);

    assert.equal(result.code, 0, result.output);
    assert.match(result.output, /0 warning\(s\), 0 failure\(s\)/);
    assert.doesNotMatch(result.output, /spec_path.*(?:must point at|unsafe or unresolved)/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint preserves defined spec_path requirements and valid ownership', () => {
  const emptyRoot = rootWithManifest();
  const invalidRoot = rootWithManifest();
  const validRoot = rootWithManifest();
  try {
    write(emptyRoot, '.dude/ideas/x.md', ledger({ status: 'defined' }));

    write(invalidRoot, '.dude/specs/x/spec.md', '# Spec\n');
    write(invalidRoot, '.dude/ideas/x.md', ledger({ status: 'defined', specPath: 'nope' }));
    write(invalidRoot, '.dude/specs/x/tasks.md', taskDocument(ideaAudit('x')));

    writeDefinedIdea(validRoot, 'x', 'x');
    write(validRoot, '.dude/specs/x/tasks.md', taskDocument(ideaAudit('x')));

    const empty = lint(emptyRoot);
    const invalid = lint(invalidRoot);
    const valid = lint(validRoot);

    assert.equal(empty.code, 1, empty.output);
    assert.match(empty.output, /status: defined but spec_path is missing/);

    assert.equal(invalid.code, 1, invalid.output);
    assert.match(invalid.output, /spec_path 'nope' must point at/);
    assert.match(invalid.output, /package \.dude\/specs\/x\/spec\.md has no defined idea owner/);

    assert.equal(valid.code, 0, valid.output);
    assert.match(valid.output, /0 warning\(s\), 0 failure\(s\)/);
    assert.doesNotMatch(valid.output, /no defined idea owner|duplicate defined idea owners/);
  } finally {
    fs.rmSync(emptyRoot, { recursive: true, force: true });
    fs.rmSync(invalidRoot, { recursive: true, force: true });
    fs.rmSync(validRoot, { recursive: true, force: true });
  }
});

test('lint counts only real idea headings outside backtick and tilde fences', () => {
  const root = rootWithManifest();
  try {
    write(
      root,
      '.dude/ideas/x.md',
      [
        '---',
        'status: draft',
        'spec_path:',
        '---',
        '',
        '```md',
        '## Idea',
        '## User Draft',
        '## Coordinator Log',
        '```',
        '',
        '~~~md',
        '## Idea',
        '## User Draft',
        '## Coordinator Log',
        '~~~',
        '',
        '## Idea',
        '',
        'Real idea.',
        '',
        '## Coordinator Log',
        '',
      ].join('\n'),
    );

    const result = lint(root);
    assert.equal(result.code, 0, result.output);
    assert.match(result.output, /Scanned: 1 idea\(s\)/);
    assert.match(result.output, /0 warning\(s\), 0 failure\(s\)/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint rejects missing, duplicate, noncanonical, mixed, and fake-only canonical headings', () => {
  const cases = [
    {
      name: 'missing idea',
      body: '## Coordinator Log\n',
      expected: /missing real '## Idea'/,
    },
    {
      name: 'duplicate idea',
      body: '## Idea\n\n## Idea\n\n## Coordinator Log\n',
      expected: /duplicate real '## Idea'/,
    },
    {
      name: 'noncanonical User Draft',
      body: '## User Draft\n\n## Coordinator Log\n',
      expected: /canonical ideas must not contain the noncanonical '## User Draft'/,
    },
    {
      name: 'mixed headings',
      body: '## Idea\n\n## User Draft\n\n## Coordinator Log\n',
      expected: /canonical ideas must not contain the noncanonical '## User Draft'/,
    },
    {
      name: 'fake-only headings',
      body: '```md\n## Idea\n## Coordinator Log\n```\n\n~~~md\n## Idea\n## Coordinator Log\n~~~\n',
      expected: /missing real '## Idea'.*outside fenced blocks/,
    },
    {
      name: 'missing Coordinator Log',
      body: '## Idea\n',
      expected: /missing real '## Coordinator Log'/,
    },
    {
      name: 'duplicate Coordinator Log',
      body: '## Idea\n\n## Coordinator Log\n\n## Coordinator Log\n',
      expected: /duplicate real '## Coordinator Log'/,
    },
  ];

  for (const fixture of cases) {
    const root = rootWithManifest();
    try {
      write(
        root,
        '.dude/ideas/x.md',
        `---\nstatus: draft\nspec_path:\n---\n\n${fixture.body}`,
      );
      const result = lint(root);
      assert.equal(result.code, 1, `${fixture.name}\n${result.output}`);
      assert.match(result.output, fixture.expected, fixture.name);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  }
});

test('lint accepts ordered managed fences and rejects unbalanced or misordered fences', () => {
  const validRoot = rootWithManifest();
  const unbalancedRoot = rootWithManifest();
  const misorderedRoot = rootWithManifest();
  try {
    write(
      validRoot,
      '.dude/ideas/x.md',
      `${ledger()}\n<!-- dude:managed:start -->\nManaged.\n<!-- dude:managed:end -->\n`,
    );
    const valid = lint(validRoot);
    assert.equal(valid.code, 0, valid.output);

    write(
      unbalancedRoot,
      '.dude/ideas/x.md',
      `${ledger()}\n<!-- dude:managed:start -->\n`,
    );
    const unbalanced = lint(unbalancedRoot);
    assert.equal(unbalanced.code, 1, unbalanced.output);
    assert.match(unbalanced.output, /unbalanced managed fences \(1 start \/ 0 end\)/);

    write(
      misorderedRoot,
      '.dude/ideas/x.md',
      `${ledger()}\n<!-- dude:managed:end -->\n<!-- dude:managed:start -->\n`,
    );
    const misordered = lint(misorderedRoot);
    assert.equal(misordered.code, 1, misordered.output);
    assert.match(misordered.output, /managed fence: end fence at line .* with no matching start/);
    assert.match(misordered.output, /managed fence: unclosed start fence opened at line/);
  } finally {
    fs.rmSync(validRoot, { recursive: true, force: true });
    fs.rmSync(unbalancedRoot, { recursive: true, force: true });
    fs.rmSync(misorderedRoot, { recursive: true, force: true });
  }
});

test('lint rejects nested directories and non-Markdown files in canonical ideas', () => {
  const root = rootWithManifest();
  try {
    write(root, '.dude/ideas/nested/x.md', ledger());
    write(root, '.dude/ideas/readme.txt', 'not an idea ledger\n');

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /\.dude\/ideas\/nested.*unsupported nested directory in canonical ideas/);
    assert.match(result.output, /\.dude\/ideas\/readme\.txt.*unsupported non-Markdown file in canonical ideas/);
    assert.match(result.output, /Scanned: 0 idea\(s\)/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint rejects symbolic links in canonical ideas without reading their targets', { skip: process.platform === 'win32' }, () => {
  const root = rootWithManifest();
  const outside = fs.mkdtempSync(path.join(os.tmpdir(), 'dude-lint-outside-'));
  try {
    write(outside, 'secret.md', 'SECRET_SENTINEL\n');
    fs.mkdirSync(path.join(root, '.dude/ideas'), { recursive: true });
    fs.symlinkSync(path.join(outside, 'secret.md'), path.join(root, '.dude/ideas/link.md'));

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /\.dude\/ideas\/link\.md.*unsupported symbolic link in canonical ideas/);
    assert.doesNotMatch(result.output, /SECRET_SENTINEL/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
    fs.rmSync(outside, { recursive: true, force: true });
  }
});

test('lint rejects FIFO entries in canonical ideas as non-regular', { skip: process.platform === 'win32' }, (context) => {
  const root = rootWithManifest();
  try {
    fs.mkdirSync(path.join(root, '.dude/ideas'), { recursive: true });
    const fifoPath = path.join(root, '.dude/ideas/pipe.md');
    const created = spawnSync('mkfifo', [fifoPath], { encoding: 'utf8' });
    if (created.status !== 0) {
      context.skip(`mkfifo unavailable: ${created.stderr || created.error || 'unknown error'}`);
      return;
    }

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /\.dude\/ideas\/pipe\.md.*unsupported non-regular entry in canonical ideas/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint rejects symbolic-link workspace, .dude, and ideas roots without traversal', { skip: process.platform === 'win32' }, () => {
  const actualRoot = rootWithManifest();
  const aliasParent = fs.mkdtempSync(path.join(os.tmpdir(), 'dude-lint-alias-'));
  const dudeParent = fs.mkdtempSync(path.join(os.tmpdir(), 'dude-lint-dude-link-'));
  const ideasRoot = rootWithManifest();
  const ideasOutside = fs.mkdtempSync(path.join(os.tmpdir(), 'dude-lint-ideas-link-'));
  try {
    write(actualRoot, '.dude/ideas/secret.md', 'ROOT_SECRET_SENTINEL\n');
    const alias = path.join(aliasParent, 'workspace');
    fs.symlinkSync(actualRoot, alias, 'dir');
    const rootResult = lint(alias);
    assert.equal(rootResult.code, 1, rootResult.output);
    assert.match(rootResult.output, /workspace root is unsafe because it is a symbolic link/);
    assert.doesNotMatch(rootResult.output, /ROOT_SECRET_SENTINEL|secret\.md/);

    const dudeRoot = path.join(dudeParent, 'workspace');
    const dudeOutside = path.join(dudeParent, 'outside-dude');
    fs.mkdirSync(dudeRoot, { recursive: true });
    write(
      dudeParent,
      'outside-dude/metadata/bundle-manifest.md',
      '# Bundle Manifest\n\n```json\n{"source_repo":"x","source_ref":"main","installed_ref":"main"}\n```\n',
    );
    write(dudeParent, 'outside-dude/ideas/secret.md', 'DUDE_SECRET_SENTINEL\n');
    fs.symlinkSync(dudeOutside, path.join(dudeRoot, '.dude'), 'dir');
    const dudeResult = lint(dudeRoot);
    assert.equal(dudeResult.code, 1, dudeResult.output);
    assert.match(dudeResult.output, /unsafe canonical ideas root or ancestor '\.dude' is a symbolic link/);
    assert.doesNotMatch(dudeResult.output, /DUDE_SECRET_SENTINEL|secret\.md/);

    write(ideasOutside, 'secret.md', 'IDEAS_SECRET_SENTINEL\n');
    fs.rmSync(path.join(ideasRoot, '.dude/ideas'), { recursive: true, force: true });
    fs.symlinkSync(ideasOutside, path.join(ideasRoot, '.dude/ideas'), 'dir');
    const ideasResult = lint(ideasRoot);
    assert.equal(ideasResult.code, 1, ideasResult.output);
    assert.match(ideasResult.output, /unsafe canonical ideas root or ancestor '\.dude\/ideas' is a symbolic link/);
    assert.doesNotMatch(ideasResult.output, /IDEAS_SECRET_SENTINEL|secret\.md/);
  } finally {
    fs.rmSync(actualRoot, { recursive: true, force: true });
    fs.rmSync(aliasParent, { recursive: true, force: true });
    fs.rmSync(dudeParent, { recursive: true, force: true });
    fs.rmSync(ideasRoot, { recursive: true, force: true });
    fs.rmSync(ideasOutside, { recursive: true, force: true });
  }
});

test('lint rejects symbolic-link workspace root without any downstream traversal', { skip: process.platform === 'win32' }, () => {
  const aliasParent = fs.mkdtempSync(path.join(os.tmpdir(), 'dude-lint-root-halt-'));
  const target = path.join(aliasParent, 'target');
  try {
    // Pack every downstream parser's target with malformed content. If the linter
    // traverses past the unsafe root, at least one of these surfaces an error.
    write(target, '.dude/metadata/bundle-manifest.md', '# Bundle Manifest\n\n```json\n{MANIFEST_HALT_SENTINEL}\n```\n');
    write(target, '.dude/metadata/profile.md', '# Install Profile\n\n```json\n{PROFILE_HALT_SENTINEL}\n```\n');
    write(target, '.dude/state/task-state.json', '{TASK_STATE_HALT_SENTINEL}\n');
    write(target, '.dude/ideas/leak.md', 'IDEA_HALT_SENTINEL\n');
    write(target, '.dude/specs/x/tasks.md', 'TASKS_HALT_SENTINEL not a canonical board\n');
    write(target, '.github/agents/dude-local-broken.agent.md', 'AGENT_HALT_SENTINEL\n');
    write(target, '.github/skills/dude-local-broken/SKILL.md', 'SKILL_HALT_SENTINEL\n');

    const alias = path.join(aliasParent, 'workspace');
    fs.symlinkSync(target, alias, 'dir');

    const result = lint(alias);

    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /workspace root is unsafe because it is a symbolic link/);
    // Exactly one failure (the root) and an all-zero scan prove nothing under
    // .dude or .github was read, scanned, or parsed.
    assert.match(result.output, /Scanned: 0 idea\(s\), 0 task file\(s\), 0 memory file\(s\), 0 agent\(s\)/);
    assert.match(result.output, /Findings: 0 warning\(s\), 1 failure\(s\)/);
    assert.doesNotMatch(result.output, /HALT_SENTINEL/);
    assert.doesNotMatch(
      result.output,
      /invalid current profile|malformed JSON object|manifest JSON is malformed|profile\.md has malformed JSON/,
    );
  } finally {
    fs.rmSync(aliasParent, { recursive: true, force: true });
  }
});

test('lint rejects duplicate exact spec_path owners and lists every canonical idea', () => {
  const root = rootWithManifest();
  try {
    write(root, '.dude/specs/x/spec.md', '# Spec\n');
    write(
      root,
      '.dude/ideas/alpha.md',
      ledger({ status: 'defined', specPath: '.dude/specs/x/spec.md' }),
    );
    write(
      root,
      '.dude/ideas/beta.md',
      ledger({ status: 'defined', specPath: '.dude/specs/x/spec.md' }),
    );

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(
      result.output,
      /\.dude\/specs\/x\/spec\.md  duplicate defined idea owners: \.dude\/ideas\/alpha\.md, \.dude\/ideas\/beta\.md/,
    );
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint ignores unrelated content in retired-root-shaped directories', () => {
  const root = rootWithManifest();
  try {
    write(root, '.dude/ideas/canonical.md', ledger());
    write(root, 'brief/nested/notes.txt', 'unrelated notes\n');
    write(root, '.dude/brief/archive.bin', 'unrelated archive\n');
    write(root, 'specs/example/spec.md', '# Unrelated spec\n');
    write(root, '.github/dudestuff/context.md', '# Unrelated context\n');

    const result = lint(root);

    assert.equal(result.code, 0, result.output);
    assert.match(result.output, /Scanned: 1 idea\(s\)/);
    assert.match(result.output, /0 warning\(s\), 0 failure\(s\)/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint accepts an exact line-one canonical audit with one defined idea owner', () => {
  const root = rootWithManifest();
  try {
    writeDefinedIdea(root, 'x', 'x');
    write(
      root,
      '.dude/specs/x/tasks.md',
      taskDocument(ideaAudit('x'), {
        body: [
          '# Tasks',
          '',
          '- [ ] T001@a1b2c3d4 [Shared] Todo task',
          '- [~] T002@b2c3d4e5 [Shared] In-progress task',
          '- [!] T003@c3d4e5f6 [Shared] Blocked task',
          '- [x] T004@d4e5f6a7 [Shared] Done task',
        ].join('\n'),
      }),
    );

    const result = lint(root);
    assert.equal(result.code, 0, result.output);
    assert.match(result.output, /Scanned: 1 idea\(s\), 1 task file\(s\)/);
    assert.match(result.output, /0 warning\(s\), 0 failure\(s\)/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint accepts the literal rendered board protocol before the canonical audit', () => {
  const root = rootWithManifest();
  try {
    writeDefinedIdea(root, 'x', 'x');
    write(
      root,
      '.dude/specs/x/tasks.md',
      taskDocument(ideaAudit('x'), {
        rendered: true,
        body: '# Tasks\n\n- [ ] T001@a1b2c3d4 [US1] Canonical task',
      }),
    );

    const result = lint(root);
    assert.equal(result.code, 0, result.output);
    assert.match(result.output, /Scanned: 1 idea\(s\), 1 task file\(s\)/);
    assert.match(result.output, /0 warning\(s\), 0 failure\(s\)/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint requires the audit to be the first canonical line after a rendered board', () => {
  const root = rootWithManifest();
  try {
    writeDefinedIdea(root, 'x', 'x');
    write(
      root,
      '.dude/specs/x/tasks.md',
      [
        TASK_BOARD_START,
        TASK_BOARD_NOTICE,
        TASK_BOARD_END,
        TASK_CANONICAL_NOTICE,
        '# Intervening prose',
        ideaAudit('x'),
        '',
      ].join('\n'),
    );

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /\.dude\/specs\/x\/tasks\.md:5/);
    assert.match(result.output, /first canonical line must be exactly/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint rejects late, missing, malformed-board, nested, and wrong-root audit breadcrumbs', () => {
  const cases = [
    {
      name: 'breadcrumb later in file',
      content: `# Tasks\n${ideaAudit('x')}\n`,
      expected: /first canonical line must be exactly/,
    },
    {
      name: 'missing audit',
      content: '# Tasks\n',
      expected: /first canonical line must be exactly/,
    },
    {
      name: 'malformed rendered board notice',
      content: [
        TASK_BOARD_START,
        '<!-- wrong generated notice -->',
        TASK_BOARD_END,
        TASK_CANONICAL_NOTICE,
        ideaAudit('x'),
        '',
      ].join('\n'),
      expected: /rendered board preamble is malformed or missing its generated notice/,
    },
    {
      name: 'nested idea path',
      content: '<!-- audit log: .dude/ideas/nested/x.md#coordinator-log -->\n',
      expected: /first canonical line must be exactly/,
    },
    {
      name: 'wrong-root target',
      content: '<!-- audit log: brief/x.md#coordinator-log -->\n',
      expected: /first canonical line must be exactly/,
    },
  ];

  for (const fixture of cases) {
    const root = rootWithManifest();
    try {
      writeDefinedIdea(root, 'x', 'x');
      write(root, '.dude/specs/x/tasks.md', fixture.content);
      const result = lint(root);
      assert.equal(result.code, 1, `${fixture.name}\n${result.output}`);
      assert.match(result.output, /\.dude\/specs\/x\/tasks\.md:/, fixture.name);
      assert.match(result.output, fixture.expected, fixture.name);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  }
});

test('lint reports the package, target, and candidates when an audit targets another package owner', () => {
  const root = rootWithManifest();
  try {
    writeDefinedIdea(root, 'owner', 'x');
    writeDefinedIdea(root, 'other', 'y');
    write(root, '.dude/specs/x/tasks.md', taskDocument(ideaAudit('other')));

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /audit breadcrumb target mismatch for package \.dude\/specs\/x\/spec\.md/);
    assert.match(result.output, /\.dude\/ideas\/other\.md points to \.dude\/specs\/y\/spec\.md/);
    assert.match(result.output, /unique owner is \.dude\/ideas\/owner\.md/);
    assert.match(result.output, /candidate owners: \.dude\/ideas\/owner\.md/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint reports an existing but wrong audit target and the unique package owner', () => {
  const root = rootWithManifest();
  try {
    writeDefinedIdea(root, 'owner', 'x');
    write(root, '.dude/ideas/draft.md', ledger());
    write(root, '.dude/specs/x/tasks.md', taskDocument(ideaAudit('draft')));

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /audit breadcrumb target \.dude\/ideas\/draft\.md is not a valid defined feature owner/);
    assert.match(result.output, /package \.dude\/specs\/x\/spec\.md/);
    assert.match(result.output, /candidate owners: \.dude\/ideas\/owner\.md/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint reports the package and target when no defined idea owns a task package', () => {
  const root = rootWithManifest();
  try {
    write(root, '.dude/specs/x/spec.md', '# Spec\n');
    write(root, '.dude/ideas/draft.md', ledger());
    write(root, '.dude/specs/x/tasks.md', taskDocument(ideaAudit('draft')));

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /package \.dude\/specs\/x\/spec\.md has no defined idea owner/);
    assert.match(result.output, /breadcrumb target \.dude\/ideas\/draft\.md/);
    assert.match(result.output, /candidate owners: \(none\)/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint reports a dangling audit target and the package owner candidate', () => {
  const root = rootWithManifest();
  try {
    writeDefinedIdea(root, 'owner', 'x');
    write(root, '.dude/specs/x/tasks.md', taskDocument(ideaAudit('missing')));

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /audit breadcrumb target \.dude\/ideas\/missing\.md is not a valid defined feature owner/);
    assert.match(result.output, /package \.dude\/specs\/x\/spec\.md/);
    assert.match(result.output, /candidate owners: \.dude\/ideas\/owner\.md/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint reports every duplicate task-package owner in the ownership diagnostic', () => {
  const root = rootWithManifest();
  try {
    write(root, '.dude/specs/x/spec.md', '# Spec\n');
    write(
      root,
      '.dude/ideas/alpha.md',
      ledger({ status: 'defined', specPath: '.dude/specs/x/spec.md' }),
    );
    write(
      root,
      '.dude/ideas/beta.md',
      ledger({ status: 'defined', specPath: '.dude/specs/x/spec.md' }),
    );
    write(root, '.dude/specs/x/tasks.md', taskDocument(ideaAudit('alpha')));

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /package \.dude\/specs\/x\/spec\.md does not have exactly one valid defined feature owner/);
    assert.match(result.output, /breadcrumb target \.dude\/ideas\/alpha\.md/);
    assert.match(
      result.output,
      /candidate owners: \.dude\/ideas\/alpha\.md, \.dude\/ideas\/beta\.md/,
    );
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint maps shared feature diagnostics to exact severity and output once', () => {
  const warningRoot = rootWithManifest();
  const errorRoot = rootWithManifest();
  try {
    fs.rmSync(path.join(warningRoot, '.dude/ideas'), { recursive: true, force: true });
    const warning = lint(warningRoot);
    assert.equal(warning.code, 0, warning.output);
    assert.match(
      warning.output,
      /^\[WARN\]  \.dude\/ideas  canonical ideas root is missing \[FEATURE_IDEAS_ROOT_MISSING\]$/m,
    );
    assert.equal((warning.output.match(/FEATURE_IDEAS_ROOT_MISSING/g) || []).length, 1);

    write(errorRoot, '.dude/ideas/x.md', ledger({ status: 'ready' }));
    const error = lint(errorRoot);
    assert.equal(error.code, 1, error.output);
    assert.match(
      error.output,
      /^\[FAIL\]  \.dude\/ideas\/x\.md  invalid status 'ready' \(valid: draft, defined\) \[FEATURE_STATUS_INVALID\]$/m,
    );
    assert.equal((error.output.match(/FEATURE_STATUS_INVALID/g) || []).length, 1);
  } finally {
    fs.rmSync(warningRoot, { recursive: true, force: true });
    fs.rmSync(errorRoot, { recursive: true, force: true });
  }
});

test('lint imports the feature library directly and does not reparse ownership metadata', () => {
  const source = fs.readFileSync(SCRIPT, 'utf8');
  assert.match(
    source,
    /import \{ inventoryDefinedFeatures \} from '\.\.\/dude-engine\/lib\/feature\.mjs';/,
  );
  assert.doesNotMatch(
    source,
    /feature-identity\.mjs|parseFrontmatterScalars|parseSpecIdentity|resolveSpecIdentity/,
  );
  assert.equal((source.match(/inventoryDefinedFeatures\(\{ root: ROOT \}\)/g) || []).length, 1);
});

test('lint requires a sibling spec.md for every task package', () => {
  const root = rootWithManifest();
  try {
    write(
      root,
      '.dude/ideas/x.md',
      ledger({ status: 'defined', specPath: '.dude/specs/x/spec.md' }),
    );
    write(root, '.dude/specs/x/tasks.md', taskDocument(ideaAudit('x')));

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /\.dude\/ideas\/x\.md.*spec_path '\.dude\/specs\/x\/spec\.md'/);
    assert.match(result.output, /spec identity target does not exist/);
    assert.match(
      result.output,
      /\.dude\/specs\/x\/tasks\.md.*package \.dude\/specs\/x\/spec\.md.*(?:missing|does not exist)/,
      'the task package itself must identify its missing sibling spec.md',
    );
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint rejects a non-regular sibling spec.md for a task package', () => {
  const root = rootWithManifest();
  try {
    write(
      root,
      '.dude/ideas/x.md',
      ledger({ status: 'defined', specPath: '.dude/specs/x/spec.md' }),
    );
    write(root, '.dude/specs/x/tasks.md', taskDocument(ideaAudit('x')));
    fs.mkdirSync(path.join(root, '.dude/specs/x/spec.md'));

    const result = lint(root);

    assert.equal(result.code, 1, result.output);
    assert.match(
      result.output,
      /\.dude\/specs\/x\/tasks\.md.*task package \.dude\/specs\/x\/spec\.md.*is not a regular file\/unsafe/,
    );
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint requires the exact task package identity even when a nested package has a sibling spec', () => {
  const root = rootWithManifest();
  try {
    writeDefinedIdea(root, 'x', 'x');
    write(root, '.dude/specs/x/nested/spec.md', '# Nested spec\n');
    write(root, '.dude/specs/x/nested/tasks.md', taskDocument(ideaAudit('x')));

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(
      result.output,
      /package \.dude\/specs\/x\/nested\/spec\.md has no defined idea owner/,
    );
    assert.match(result.output, /breadcrumb target \.dude\/ideas\/x\.md/);
    assert.match(result.output, /candidate owners: \(none\)/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint preserves canonical task grammar rejection diagnostics', () => {
  const cases = [
    {
      name: 'invalid glyph',
      body: '- [?] T001@a1b2c3d4 [Shared] Invalid glyph',
      expected: /invalid task glyph \[\?\] \(valid: space, ~, !, x\)/,
    },
    {
      name: 'malformed header',
      body: '- [ ] T001 [Shared] Missing durable suffix',
      expected: /malformed task header \(expected: - \[ \] T001@a1b2c3d4/,
    },
    {
      name: 'duplicate durable ID',
      body: [
        '- [ ] T001@a1b2c3d4 [Shared] First',
        '- [x] T001@a1b2c3d4 [US1] Duplicate',
      ].join('\n'),
      expected: /duplicate task ID T001@a1b2c3d4/,
    },
    {
      name: 'reserved task outside discovered section',
      body: '- [ ] T9001@a1b2c3d4 [Shared] Reserved task',
      expected: /uses reserved discovered boundary T9000-T9999 outside ## Discovered During Execution/,
    },
  ];

  for (const fixture of cases) {
    const root = rootWithManifest();
    try {
      writeDefinedIdea(root, 'x', 'x');
      write(root, '.dude/specs/x/tasks.md', taskDocument(ideaAudit('x'), { body: fixture.body }));
      const result = lint(root);
      assert.equal(result.code, 1, `${fixture.name}\n${result.output}`);
      assert.match(result.output, fixture.expected, fixture.name);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  }
});

test('lint preserves unbalanced, duplicate, and incomplete rendered board diagnostics', () => {
  const cases = [
    {
      name: 'unbalanced board',
      content: `${TASK_BOARD_START}\n${TASK_BOARD_NOTICE}\n`,
      expected: /unbalanced board fences \(1 start \/ 0 end\)/,
    },
    {
      name: 'duplicate boards',
      content: [
        TASK_BOARD_START,
        TASK_BOARD_NOTICE,
        TASK_BOARD_END,
        TASK_BOARD_START,
        TASK_BOARD_NOTICE,
        TASK_BOARD_END,
        TASK_CANONICAL_NOTICE,
        ideaAudit('x'),
        '',
      ].join('\n'),
      expected: /multiple board fence pairs found \(2\); expected 0 or 1/,
    },
    {
      name: 'missing canonical notice',
      content: [
        TASK_BOARD_START,
        TASK_BOARD_NOTICE,
        TASK_BOARD_END,
        ideaAudit('x'),
        '',
      ].join('\n'),
      expected: /rendered board preamble must be followed by '<!-- canonical task units/,
    },
  ];

  for (const fixture of cases) {
    const root = rootWithManifest();
    try {
      writeDefinedIdea(root, 'x', 'x');
      write(root, '.dude/specs/x/tasks.md', fixture.content);
      const result = lint(root);
      assert.equal(result.code, 1, `${fixture.name}\n${result.output}`);
      assert.match(result.output, fixture.expected, fixture.name);
      assert.match(result.output, /first canonical line must be the exact audit breadcrumb/, fixture.name);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  }
});

test('lint preserves discovered-task boundaries and Beads tag warnings', () => {
  const validRoot = rootWithManifest();
  const warningRoot = rootWithManifest();
  try {
    writeDefinedIdea(validRoot, 'x', 'x');
    write(
      validRoot,
      '.dude/specs/x/tasks.md',
      taskDocument(ideaAudit('x'), {
        body: '## Discovered During Execution\n- [ ] T9001@a1b2c3d4 [Shared] Found (Beads: dude-1)',
      }),
    );
    const valid = lint(validRoot);
    assert.equal(valid.code, 0, valid.output);
    assert.match(valid.output, /0 warning\(s\), 0 failure\(s\)/);

    writeDefinedIdea(warningRoot, 'x', 'x');
    write(
      warningRoot,
      '.dude/specs/x/tasks.md',
      taskDocument(ideaAudit('x'), {
        body: '## Discovered During Execution\n- [ ] T9001@a1b2c3d4 [Shared] Missing Beads tag',
      }),
    );
    const warning = lint(warningRoot);
    assert.equal(warning.code, 0, warning.output);
    assert.match(warning.output, /task T9001@a1b2c3d4.*missing its \(Beads: <id>\) tag/);
    assert.match(warning.output, /Findings: 1 warning\(s\), 0 failure\(s\)/);
  } finally {
    fs.rmSync(validRoot, { recursive: true, force: true });
    fs.rmSync(warningRoot, { recursive: true, force: true });
  }
});

test('lint rejects non-reserved tasks in the discovered section', () => {
  const discoveredRoot = rootWithManifest();
  try {
    writeDefinedIdea(discoveredRoot, 'x', 'x');
    write(
      discoveredRoot,
      '.dude/specs/x/tasks.md',
      taskDocument(ideaAudit('x'), {
        body: '## Discovered During Execution\n- [ ] T001@a1b2c3d4 [Shared] Wrong range (Beads: dude-1)',
      }),
    );
    const discovered = lint(discoveredRoot);
    assert.equal(discovered.code, 1, discovered.output);
    assert.match(discovered.output, /task T001@a1b2c3d4.*must be in reserved range T9001-T9999/);
  } finally {
    fs.rmSync(discoveredRoot, { recursive: true, force: true });
  }
});

test('lint preserves duplicate and final-position execution history diagnostics', () => {
  const root = rootWithManifest();
  try {
    writeDefinedIdea(root, 'x', 'x');
    write(
      root,
      '.dude/specs/x/tasks.md',
      taskDocument(ideaAudit('x'), {
        body: [
          '## Lightweight Execution History',
          'Historical prose.',
          '## Later Phase',
          '- [ ] T001@a1b2c3d4 [Shared] Too late',
          '## Lightweight Execution History',
          'Duplicate history.',
        ].join('\n'),
      }),
    );

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /canonical task row T001@a1b2c3d4 appears below ## Lightweight Execution History/);
    assert.match(result.output, /duplicate ## Lightweight Execution History section/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint requires and strictly parses the current canonical profile', () => {
  const missingRoot = rootWithManifest();
  const malformedRoot = rootWithManifest();
  const invalidRoot = rootWithManifest();
  try {
    fs.rmSync(path.join(missingRoot, '.dude/metadata/profile.md'));
    write(malformedRoot, '.dude/metadata/profile.md', '# Install Profile\n\n```json\n{nope}\n```\n');
    write(
      invalidRoot,
      '.dude/metadata/profile.md',
      profileDocument({ enabled_packs: [], installed: {}, unsupported: true }),
    );

    const missing = lint(missingRoot);
    const malformed = lint(malformedRoot);
    const invalid = lint(invalidRoot);

    assert.equal(missing.code, 1, missing.output);
    assert.match(missing.output, /\.dude\/metadata\/profile\.md  missing current canonical profile/);

    assert.equal(malformed.code, 1, malformed.output);
    assert.match(malformed.output, /\.dude\/metadata\/profile\.md  invalid current profile/);
    assert.match(malformed.output, /profile\.md has malformed JSON/);

    assert.equal(invalid.code, 1, invalid.output);
    assert.match(invalid.output, /\.dude\/metadata\/profile\.md  invalid current profile/);
    assert.match(invalid.output, /must contain only enabled_packs and installed/);

    for (const result of [missing, malformed, invalid]) {
      assert.doesNotMatch(result.output, /migrat|schema-v0/i);
    }
  } finally {
    fs.rmSync(missingRoot, { recursive: true, force: true });
    fs.rmSync(malformedRoot, { recursive: true, force: true });
    fs.rmSync(invalidRoot, { recursive: true, force: true });
  }
});

test('lint requires a complete current inventory for every installed profile entry', () => {
  const missingInventoryRoot = rootWithManifest();
  const partialInventoryRoot = rootWithManifest();
  const entry = {
    files: ['.github/prompts/dude-pack-demo-review.prompt.md'],
    installed_at: '2026-07-13T00:00:00.000Z',
  };
  try {
    write(
      missingInventoryRoot,
      '.dude/metadata/profile.md',
      profileDocument({ enabled_packs: ['demo'], installed: { demo: entry } }),
    );
    write(
      partialInventoryRoot,
      '.dude/metadata/profile.md',
      profileDocument({
        enabled_packs: ['demo'],
        installed: { demo: { ...entry, inventory: { version: 1, pack: 'demo' } } },
      }),
    );

    const missingInventory = lint(missingInventoryRoot);
    const partialInventory = lint(partialInventoryRoot);

    for (const result of [missingInventory, partialInventory]) {
      assert.equal(result.code, 1, result.output);
      assert.match(
        result.output,
        /\.dude\/metadata\/profile\.md  installed\.demo must include a complete current inventory/,
      );
      assert.doesNotMatch(result.output, /migrat|schema-v0/i);
    }
  } finally {
    fs.rmSync(missingInventoryRoot, { recursive: true, force: true });
    fs.rmSync(partialInventoryRoot, { recursive: true, force: true });
  }
});

test('lint accepts empty and complete non-empty current profiles', () => {
  const emptyRoot = rootWithManifest();
  const installedRoot = rootWithManifest();
  try {
    write(installedRoot, '.dude/metadata/profile.md', profileDocument(completeCurrentProfile()));

    const empty = lint(emptyRoot);
    const installed = lint(installedRoot);

    assert.equal(empty.code, 0, empty.output);
    assert.match(empty.output, /0 warning\(s\), 0 failure\(s\)/);
    assert.equal(installed.code, 0, installed.output);
    assert.match(installed.output, /0 warning\(s\), 0 failure\(s\)/);
  } finally {
    fs.rmSync(emptyRoot, { recursive: true, force: true });
    fs.rmSync(installedRoot, { recursive: true, force: true });
  }
});

test('lint requires exact enabled and installed pack equality', () => {
  const equalRoot = rootWithManifest();
  const enabledExtraRoot = rootWithManifest();
  const installedExtraRoot = rootWithManifest();
  try {
    // Exact equality (non-empty) passes.
    write(equalRoot, '.dude/metadata/profile.md', profileDocument(completeCurrentProfile()));

    // enabled_packs lists a pack that is not installed. parseProfileDocument
    // permits enabled ⊋ installed, so lint must close this direction itself.
    write(
      enabledExtraRoot,
      '.dude/metadata/profile.md',
      profileDocument({ enabled_packs: ['ghost'], installed: {} }),
    );

    // installed carries a pack absent from enabled_packs (the other direction).
    write(
      installedExtraRoot,
      '.dude/metadata/profile.md',
      profileDocument({
        enabled_packs: [],
        installed: { ghost: { files: [], installed_at: '2026-07-13T00:00:00.000Z' } },
      }),
    );

    const equal = lint(equalRoot);
    const enabledExtra = lint(enabledExtraRoot);
    const installedExtra = lint(installedExtraRoot);

    assert.equal(equal.code, 0, equal.output);
    assert.match(equal.output, /0 warning\(s\), 0 failure\(s\)/);

    assert.equal(enabledExtra.code, 1, enabledExtra.output);
    assert.match(
      enabledExtra.output,
      /\.dude\/metadata\/profile\.md  enabled pack\(s\) not installed: ghost/,
    );

    assert.equal(installedExtra.code, 1, installedExtra.output);
    assert.match(
      installedExtra.output,
      /\.dude\/metadata\/profile\.md  invalid current profile \(profile\.md installed pack 'ghost' is not listed in enabled_packs\)/,
    );
  } finally {
    fs.rmSync(equalRoot, { recursive: true, force: true });
    fs.rmSync(enabledExtraRoot, { recursive: true, force: true });
    fs.rmSync(installedExtraRoot, { recursive: true, force: true });
  }
});

test('lint accepts a missing optional task-state snapshot', () => {
  const root = rootWithManifest();
  try {
    assert.equal(fs.existsSync(path.join(root, '.dude/state/task-state.json')), false);
    const result = lint(root);
    assert.equal(result.code, 0, result.output);
    assert.match(result.output, /0 warning\(s\), 0 failure\(s\)/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('lint rejects final metadata symlinks without parsing malformed external targets', { skip: process.platform === 'win32' }, () => {
  const fixtures = [
    {
      relPath: '.dude/metadata/profile.md',
      externalContent: '# Install Profile\n\n```json\n{PROFILE_PARSE_SENTINEL}\n```\n',
      forbidden: /PROFILE_PARSE_SENTINEL|invalid current profile|profile\.md has malformed JSON/,
    },
    {
      relPath: '.dude/state/task-state.json',
      externalContent: '{TASK_STATE_PARSE_SENTINEL}\n',
      forbidden: /TASK_STATE_PARSE_SENTINEL|malformed JSON object/,
    },
    {
      relPath: '.dude/metadata/bundle-manifest.md',
      externalContent: '# Bundle Manifest\n\n```json\n{MANIFEST_PARSE_SENTINEL}\n```\n',
      forbidden: /MANIFEST_PARSE_SENTINEL|manifest JSON is malformed/,
    },
  ];

  for (const fixture of fixtures) {
    const root = rootWithManifest();
    const outside = fs.mkdtempSync(path.join(os.tmpdir(), 'dude-lint-metadata-link-'));
    try {
      const external = path.join(outside, path.basename(fixture.relPath));
      fs.writeFileSync(external, fixture.externalContent);
      const target = path.join(root, fixture.relPath);
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.rmSync(target, { force: true });
      fs.symlinkSync(external, target);

      const result = lint(root);
      assert.equal(result.code, 1, `${fixture.relPath}\n${result.output}`);
      assert.match(
        result.output,
        new RegExp(`${fixture.relPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}  is not a regular file/unsafe because .* is a symbolic link`),
      );
      assert.doesNotMatch(result.output, fixture.forbidden, fixture.relPath);
      assert.match(result.output, /Findings: 0 warning\(s\), 1 failure\(s\)/);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
      fs.rmSync(outside, { recursive: true, force: true });
    }
  }
});

test('lint rejects metadata ancestor symlinks without parsing profile or manifest targets', { skip: process.platform === 'win32' }, () => {
  const root = rootWithManifest();
  const outside = fs.mkdtempSync(path.join(os.tmpdir(), 'dude-lint-metadata-ancestor-'));
  try {
    write(outside, 'profile.md', '# Install Profile\n\n```json\n{PROFILE_ANCESTOR_SENTINEL}\n```\n');
    write(outside, 'bundle-manifest.md', '# Bundle Manifest\n\n```json\n{MANIFEST_ANCESTOR_SENTINEL}\n```\n');
    fs.rmSync(path.join(root, '.dude/metadata'), { recursive: true, force: true });
    fs.symlinkSync(outside, path.join(root, '.dude/metadata'), 'dir');

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /\.dude\/metadata\/profile\.md  is not a regular file\/unsafe because '\.dude\/metadata' is a symbolic link/);
    assert.match(result.output, /\.dude\/metadata\/bundle-manifest\.md  is not a regular file\/unsafe because '\.dude\/metadata' is a symbolic link/);
    assert.doesNotMatch(result.output, /ANCESTOR_SENTINEL|invalid current profile|manifest JSON is malformed/);
    assert.match(result.output, /Findings: 0 warning\(s\), 2 failure\(s\)/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
    fs.rmSync(outside, { recursive: true, force: true });
  }
});

test('lint rejects task-state ancestor symlinks without parsing malformed targets', { skip: process.platform === 'win32' }, () => {
  const root = rootWithManifest();
  const outside = fs.mkdtempSync(path.join(os.tmpdir(), 'dude-lint-state-ancestor-'));
  try {
    write(outside, 'task-state.json', '{TASK_STATE_ANCESTOR_SENTINEL}\n');
    fs.symlinkSync(outside, path.join(root, '.dude/state'), 'dir');

    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /\.dude\/state\/task-state\.json  is not a regular file\/unsafe because '\.dude\/state' is a symbolic link/);
    assert.doesNotMatch(result.output, /TASK_STATE_ANCESTOR_SENTINEL|malformed JSON object/);
    assert.match(result.output, /Findings: 0 warning\(s\), 1 failure\(s\)/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
    fs.rmSync(outside, { recursive: true, force: true });
  }
});

test('lint rejects malformed task-state JSON objects and non-canonical keys', () => {
  const malformedRoot = rootWithManifest();
  const nestedKeyRoot = rootWithManifest();
  try {
    write(malformedRoot, '.dude/state/task-state.json', '[]\n');
    const malformed = lint(malformedRoot);
    assert.equal(malformed.code, 1, malformed.output);
    assert.match(malformed.output, /\.dude\/state\/task-state\.json  malformed JSON object/);

    write(
      nestedKeyRoot,
      '.dude/state/task-state.json',
      '{".dude/specs/x/nested/tasks.md":{"glyphs":{}}}\n',
    );
    const nestedKey = lint(nestedKeyRoot);
    assert.equal(nestedKey.code, 1, nestedKey.output);
    assert.match(nestedKey.output, /invalid task-state key '\.dude\/specs\/x\/nested\/tasks\.md'/);
  } finally {
    fs.rmSync(malformedRoot, { recursive: true, force: true });
    fs.rmSync(nestedKeyRoot, { recursive: true, force: true });
  }
});

test('lint preserves canonical bundle-manifest schema diagnostics', () => {
  const cases = [
    {
      name: 'missing canonical manifest',
      content: null,
      expected: /\.dude\/metadata\/bundle-manifest\.md  missing seeded bundle manifest/,
    },
    {
      name: 'missing fenced JSON',
      content: '# Bundle Manifest\n',
      expected: /missing fenced JSON manifest block/,
    },
    {
      name: 'malformed JSON',
      content: '# Bundle Manifest\n\n```json\n{nope}\n```\n',
      expected: /manifest JSON is malformed/,
    },
    {
      name: 'unsupported field',
      content: '# Bundle Manifest\n\n```json\n{"source_repo":"x","source_ref":"main","extra":true}\n```\n',
      expected: /manifest has unsupported field 'extra'/,
    },
    {
      name: 'missing source repo',
      content: '# Bundle Manifest\n\n```json\n{"source_ref":"main"}\n```\n',
      expected: /manifest is missing source_repo/,
    },
    {
      name: 'missing source ref',
      content: '# Bundle Manifest\n\n```json\n{"source_repo":"x"}\n```\n',
      expected: /manifest is missing source_ref/,
    },
    {
      name: 'non-string installed ref',
      content: '# Bundle Manifest\n\n```json\n{"source_repo":"x","source_ref":"main","installed_ref":1}\n```\n',
      expected: /installed_ref must be a string/,
    },
  ];

  for (const fixture of cases) {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'dude-lint-manifest-'));
    try {
      write(root, '.dude/metadata/profile.md', profileDocument({ enabled_packs: [], installed: {} }));
      if (fixture.content !== null) write(root, '.dude/metadata/bundle-manifest.md', fixture.content);
      const result = lint(root);
      assert.equal(result.code, 1, `${fixture.name}\n${result.output}`);
      assert.match(result.output, fixture.expected, fixture.name);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  }
});

test('lint rejects a noncanonical task-state identity without migration guidance', () => {
  const root = rootWithManifest();
  try {
    write(root, '.dude/state/task-state.json', '{"specs/x/tasks.md":{"glyphs":{}}}\n');
    const result = lint(root);
    assert.equal(result.code, 1, result.output);
    assert.match(result.output, /invalid task-state key 'specs\/x\/tasks\.md'/);
    assert.doesNotMatch(result.output, /migrate/);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

// T037: lint Check 2b validates the exact task-state schema (not just the top
// object and its keys). A present-but-wrong-schema snapshot is corruption and
// must fail with a reason. The current lint only checks the top object and key
// shape, so these deeper-schema fixtures pass today -> BEHAVIORAL-RED now.
test('lint fails on a wrong-schema task-state snapshot with a reason', () => {
  const cases = [
    {
      name: 'bad glyph value',
      body: `${JSON.stringify(
        { '.dude/specs/x/tasks.md': { glyphs: { 'T001@aaaaaaaa': 'z' }, updated_at: '2026-01-01T00:00:00.000Z' } },
        null,
        2,
      )}\n`,
    },
    {
      name: 'entry missing updated_at',
      body: `${JSON.stringify(
        { '.dude/specs/x/tasks.md': { glyphs: { 'T001@aaaaaaaa': 'x' } } },
        null,
        2,
      )}\n`,
    },
    {
      name: 'entry extra field',
      body: `${JSON.stringify(
        { '.dude/specs/x/tasks.md': { glyphs: {}, updated_at: '2026-01-01T00:00:00.000Z', extra: true } },
        null,
        2,
      )}\n`,
    },
    {
      name: 'bad task key',
      body: `${JSON.stringify(
        { '.dude/specs/x/tasks.md': { glyphs: { nope: 'x' }, updated_at: '2026-01-01T00:00:00.000Z' } },
        null,
        2,
      )}\n`,
    },
  ];

  for (const fixture of cases) {
    const root = rootWithManifest();
    try {
      write(root, '.dude/state/task-state.json', fixture.body);
      const result = lint(root);
      assert.equal(result.code, 1, `${fixture.name}\n${result.output}`);
      // `[FAIL]  <path>  <reason>` — a nonempty reason must follow the path.
      assert.match(result.output, /\.dude\/state\/task-state\.json {2}\S/, fixture.name);
      assert.doesNotMatch(result.output, /0 failure\(s\)/, fixture.name);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  }
});

// T037: absence stays clean, and a fully valid snapshot (empty or populated)
// lints clean. These are GREEN now (current lint tolerates them) and lock in the
// same behavior after the strict schema validation lands.
test('lint accepts a valid empty and a valid populated task-state snapshot', () => {
  const emptyRoot = rootWithManifest();
  const populatedRoot = rootWithManifest();
  try {
    write(emptyRoot, '.dude/state/task-state.json', '{}\n');
    const empty = lint(emptyRoot);
    assert.equal(empty.code, 0, empty.output);
    assert.match(empty.output, /0 warning\(s\), 0 failure\(s\)/);

    write(
      populatedRoot,
      '.dude/state/task-state.json',
      `${JSON.stringify(
        {
          '.dude/specs/x/tasks.md': {
            glyphs: { 'T001@aaaaaaaa': 'x', 'T002@bbbbbbbb': ' ' },
            updated_at: '2026-01-01T00:00:00.000Z',
          },
        },
        null,
        2,
      )}\n`,
    );
    const populated = lint(populatedRoot);
    assert.equal(populated.code, 0, populated.output);
    assert.match(populated.output, /0 warning\(s\), 0 failure\(s\)/);
  } finally {
    fs.rmSync(emptyRoot, { recursive: true, force: true });
    fs.rmSync(populatedRoot, { recursive: true, force: true });
  }
});

// FR-029 (T034): lint aggregates the feature library's strict owner-metadata
// diagnostics. A ledger that violates the canonical grammar must be reported
// with its code and exit non-zero. (The 'lint imports the feature library
// directly' guard above stays green because lint.mjs is not modified.)
test('lint reports strict owner-metadata violations from the feature library and exits non-zero', () => {
  const specPath = '.dude/specs/x/spec.md';
  const cases = [
    { name: 'noncanonical key', violation: 'priority: high' },
    { name: 'quoted canonical key', violation: '"title": Example' },
    { name: 'unsupported top-level list entry', violation: '- orphan' },
  ];

  for (const fixture of cases) {
    const root = rootWithManifest();
    try {
      write(root, specPath, '# Spec\n');
      const content = ledger({ status: 'defined', specPath })
        .replace(`spec_path: ${specPath}\n---`, `spec_path: ${specPath}\n${fixture.violation}\n---`);
      write(root, '.dude/ideas/x.md', content);

      const result = lint(root);

      assert.equal(result.code, 1, `${fixture.name}\n${result.output}`);
      assert.match(result.output, /\.dude\/ideas\/x\.md/, fixture.name);
      assert.match(result.output, /FEATURE_FRONTMATTER_MALFORMED/, fixture.name);
    } finally {
      fs.rmSync(root, { recursive: true, force: true });
    }
  }
});
