// @ts-check
/**
 * Dude `tasks.md` engine — pure parse / derive / render / mutate logic for the
 * Lightweight Execution board, plus the coordinator-state snapshot used to
 * detect human-applied `[x]` without evidence.
 *
 * This is the single source of truth for the `tasks.md` grammar. The CLI wrapper
 * `dude-lightweight-execution/board.mjs` is a thin shell over these functions.
 * Dependency-free ESM, Node >= 20. All logic functions are pure (operate on
 * strings/objects); only the snapshot helpers touch the filesystem.
 *
 * Grammar (see dude-lightweight-execution/SKILL.md):
 *   - Board fence: `<!-- dude:board:start -->` ... `<!-- dude:board:end -->`.
 *     Everything inside is a derived view and is ignored when parsing canonical
 *     state. Regenerated as a complete replacement, never patched in place.
 *   - Canonical task header:
 *       `- [<glyph>] T<num>@<sha8>[ [P]][ [<label>]] <description>`
 *     glyph in { ' ', '~', '!', 'x' } -> { todo, in-progress, blocked, done }.
 *   - Continuation metadata: indented lines under a header. Recognized keys:
 *     `deps: <id>, <id>` and `blocked-by: <text>`; other indented lines are
 *     preserved verbatim.
 *   - Phases inferred from `##`/`###` headings (Setup, Foundational, User Story
 *     <n>, Polish); a task belongs to the nearest preceding phase heading.
 *   - Malformed/duplicate IDs and dangling `deps` targets do not throw; they are
 *     recorded in `warnings[]` and treated as unsatisfied where relevant.
 */

export const BOARD_START = '<!-- dude:board:start -->';
export const BOARD_END = '<!-- dude:board:end -->';
export const BOARD_NOTICE =
  '<!-- generated by @dude — do not hand-edit; regenerated on every status/define refresh -->';
export const CANONICAL_NOTICE =
  '<!-- canonical task units — edit task descriptions here, but let @dude mutate state glyphs -->';

/** @type {Record<string, string>} glyph -> state name */
export const GLYPH_STATE = { ' ': 'todo', '~': 'in-progress', '!': 'blocked', x: 'done' };
/** @type {Record<string, string>} state name -> glyph */
export const STATE_GLYPH = { todo: ' ', 'in-progress': '~', blocked: '!', done: 'x' };

const HEADER_RE = /^- \[( |~|!|x)\] (T\d{3,}@[a-z0-9]{8})( \[P\])?( \[[^\]]+\])? (.+)$/;
const LOOSE_HEADER_RE = /^- \[[^\]]*\]/;
const HEADING_RE = /^#{2,3}\s+(.+?)\s*$/;

/**
 * Map a heading to a stable ordering key. Lower sorts earlier.
 * @param {string} heading
 * @returns {number}
 */
function phaseOrder(heading) {
  const t = heading.toLowerCase();
  if (/\bsetup\b/.test(t)) return 0 * 1000;
  if (/\bfoundational\b|\bfoundation\b/.test(t)) return 1 * 1000;
  const us = /user stor(?:y|ies)\s*(\d+)?/.exec(t);
  if (us) return 2 * 1000 + Number(us[1] || 0);
  if (/\bpolish\b/.test(t)) return 4 * 1000;
  return 3 * 1000; // unknown headings sort between user stories and polish
}

/**
 * @typedef {Object} Task
 * @property {string} id            durable key, e.g. `T001@a1b2c3d4`
 * @property {number} num           numeric part of the ID (for ordering)
 * @property {string} glyph         one of ' ', '~', '!', 'x'
 * @property {string} state         todo | in-progress | blocked | done
 * @property {boolean} parallel     whether the `[P]` flag is present
 * @property {string|null} label    optional `[US1|Shared]`-style label (without brackets)
 * @property {string} description
 * @property {string[]} deps        dependency IDs from `deps:`
 * @property {string|null} blockedBy
 * @property {string[]} extraMeta   other indented metadata lines, verbatim
 * @property {number} headerLine    0-based line index of the header
 * @property {number} order         phase ordering key
 */

/**
 * Parse `tasks.md` content into canonical task units + board metadata.
 * @param {string} content
 * @param {{ path?: string }} [opts]
 * @returns {{ path: string|null, lines: string[], board: {startLine:number,endLine:number}|null, tasks: Task[], byId: Map<string,Task>, warnings: string[] }}
 */
export function parseTasks(content, opts = {}) {
  const lines = String(content).split('\n');
  /** @type {string[]} */
  const warnings = [];

  // Locate the board fence (first start..end pair).
  let startLine = -1;
  let endLine = -1;
  for (let i = 0; i < lines.length; i++) {
    if (startLine === -1 && lines[i].trim() === BOARD_START) startLine = i;
    else if (startLine !== -1 && lines[i].trim() === BOARD_END) {
      endLine = i;
      break;
    }
  }
  const board = startLine !== -1 && endLine !== -1 ? { startLine, endLine } : null;
  const inBoard = (i) => board !== null && i >= board.startLine && i <= board.endLine;

  /** @type {Task[]} */
  const tasks = [];
  /** @type {Map<string, Task>} */
  const byId = new Map();
  let currentOrder = 3 * 1000; // default bucket before any heading
  /** @type {Task | null} */
  let current = null;

  for (let i = 0; i < lines.length; i++) {
    if (inBoard(i)) {
      current = null;
      continue;
    }
    const line = lines[i];

    const heading = HEADING_RE.exec(line);
    if (heading) {
      currentOrder = phaseOrder(heading[1]);
      current = null;
      continue;
    }

    const m = HEADER_RE.exec(line);
    if (m) {
      const id = m[2];
      const num = Number(/^T(\d+)@/.exec(id)?.[1] || 0);
      /** @type {Task} */
      const task = {
        id,
        num,
        glyph: m[1],
        state: GLYPH_STATE[m[1]],
        parallel: Boolean(m[3]),
        label: m[4] ? m[4].trim().replace(/^\[|\]$/g, '') : null,
        description: m[5],
        deps: [],
        blockedBy: null,
        extraMeta: [],
        headerLine: i,
        order: currentOrder,
      };
      if (byId.has(id)) warnings.push(`duplicate task id ${id} at line ${i + 1}`);
      else byId.set(id, task);
      tasks.push(task);
      current = task;
      continue;
    }

    // Indented continuation metadata belongs to the current task.
    if (current && /^\s+\S/.test(line)) {
      const dep = /^\s*deps:\s*(.+)$/.exec(line);
      const bb = /^\s*blocked-by:\s*(.+)$/.exec(line);
      if (dep) {
        current.deps.push(...dep[1].split(',').map((s) => s.trim()).filter(Boolean));
      } else if (bb) {
        current.blockedBy = bb[1].trim();
      } else {
        current.extraMeta.push(line);
      }
      continue;
    }

    // A line that looks like a task but does not match the strict grammar.
    if (!inBoard(i) && LOOSE_HEADER_RE.test(line) && !HEADER_RE.test(line)) {
      warnings.push(`malformed task line ${i + 1}: ${line.trim()}`);
    }
    if (line.trim() === '') current = null;
  }

  // Dangling dependency detection.
  for (const t of tasks) {
    for (const d of t.deps) {
      if (!byId.has(d)) warnings.push(`task ${t.id} depends on unknown id ${d}`);
    }
  }

  return { path: opts.path || null, lines, board, tasks, byId, warnings };
}

/**
 * @param {ReturnType<typeof parseTasks>} parsed
 * @param {Task} t
 * @returns {boolean} true when every dependency exists and is done.
 */
function depsSatisfied(parsed, t) {
  return t.deps.every((d) => parsed.byId.get(d)?.state === 'done');
}

/**
 * Ready tasks: `todo` glyph with every dependency satisfied. In-progress and
 * blocked tasks are surfaced in their own board sections, not here. Sorted by
 * phase order then task number (deterministic).
 * @param {ReturnType<typeof parseTasks>} parsed
 * @returns {Task[]}
 */
export function readyTasks(parsed) {
  return parsed.tasks
    .filter((t) => t.state === 'todo' && depsSatisfied(parsed, t))
    .sort((a, b) => a.order - b.order || a.num - b.num);
}

/**
 * @param {ReturnType<typeof parseTasks>} parsed
 * @returns {Task | null} the single top ready task, or null.
 */
export function nextTask(parsed) {
  return readyTasks(parsed)[0] || null;
}

/**
 * Derive the implied dependency graph of a `tasks.md`, used when importing into
 * a tracker (e.g. Beads). Deterministic. Edge `{from, to}` means `from` depends
 * on `to` (to must finish first). Rules mirror the import algorithm:
 *   1. explicit `deps:` become direct edges;
 *   2. phase gating — every task depends on all tasks in the immediately
 *      preceding phase (transitively gates earlier phases too);
 *   3. intra-phase ordering — a non-`[P]` task depends on all earlier tasks in
 *      its own phase; `[P]` tasks have no sibling edges beyond explicit `deps`.
 * Duplicate and self edges are removed.
 * @param {ReturnType<typeof parseTasks>} parsed
 * @returns {{ from: string, to: string }[]}
 */
export function deriveDependencies(parsed) {
  const tasks = parsed.tasks;
  const phases = [...new Set(tasks.map((t) => t.order))].sort((a, b) => a - b);
  /** @type {Map<number, Task[]>} */
  const byPhase = new Map(
    phases.map((o) => [o, tasks.filter((t) => t.order === o).sort((a, b) => a.num - b.num)]),
  );
  /** @type {{from:string,to:string}[]} */
  const edges = [];
  const seen = new Set();
  const add = (from, to) => {
    if (from === to) return;
    const k = `${from}\u0000${to}`;
    if (!seen.has(k)) {
      seen.add(k);
      edges.push({ from, to });
    }
  };
  // 1. explicit deps (only to known ids)
  for (const t of tasks) for (const d of t.deps) if (parsed.byId.has(d)) add(t.id, d);
  // 2. phase gating: depend on all tasks in the immediately preceding phase
  for (let i = 1; i < phases.length; i++) {
    const prev = byPhase.get(phases[i - 1]) || [];
    for (const t of byPhase.get(phases[i]) || []) for (const p of prev) add(t.id, p.id);
  }
  // 3. intra-phase ordering for non-[P] tasks
  for (const o of phases) {
    const group = byPhase.get(o) || [];
    for (let i = 0; i < group.length; i++) {
      if (group[i].parallel) continue;
      for (let j = 0; j < i; j++) add(group[i].id, group[j].id);
    }
  }
  return edges;
}

/** @param {Task} t @returns {string} board line for a task */
function boardEntry(t) {
  return `- ${t.id}${t.label ? ` [${t.label}]` : ''} ${t.description}`;
}

/**
 * Build the managed board block (fence + notice + sections + fence + canonical
 * notice) as an array of lines.
 * @param {ReturnType<typeof parseTasks>} parsed
 * @returns {string[]}
 */
function buildBoardBlock(parsed) {
  const ready = readyTasks(parsed);
  const inProgress = parsed.tasks.filter((t) => t.state === 'in-progress');
  const blocked = parsed.tasks.filter((t) => t.state === 'blocked');
  const done = parsed.tasks.filter((t) => t.state === 'done');
  /** @param {string} title @param {Task[]} items */
  const section = (title, items) => [
    `### ${title}`,
    ...(items.length ? items.map(boardEntry) : ['- (none)']),
    '',
  ];
  return [
    BOARD_START,
    BOARD_NOTICE,
    '',
    ...section('Ready Now', ready),
    ...section('In Progress', inProgress),
    ...section('Blocked', blocked),
    ...section('Done', done),
    BOARD_END,
    '',
    CANONICAL_NOTICE,
  ];
}

/**
 * Find the insertion anchor for a fresh board (no existing fence): after a
 * leading H1 title if present within the first two non-blank lines, else 0.
 * @param {string[]} lines
 * @returns {number} index at which the board block should start
 */
function freshAnchor(lines) {
  for (let i = 0; i < Math.min(lines.length, 3); i++) {
    if (/^#\s+\S/.test(lines[i])) return i + 1;
    if (lines[i].trim() !== '') break;
  }
  return 0;
}

/**
 * Regenerate the board region as a complete replacement. Pure: returns the new
 * full file content, never writes.
 * @param {ReturnType<typeof parseTasks>} parsed
 * @returns {string}
 */
export function renderBoard(parsed) {
  const lines = parsed.lines.slice();
  const block = buildBoardBlock(parsed);

  let pre;
  let post;
  if (parsed.board) {
    // Replace the existing managed block: fence region + an adjacent canonical
    // notice (skipping blank lines) if present.
    let mEnd = parsed.board.endLine;
    let j = mEnd + 1;
    while (j < lines.length && lines[j].trim() === '') j++;
    if (j < lines.length && lines[j].trim() === CANONICAL_NOTICE) mEnd = j;
    pre = lines.slice(0, parsed.board.startLine);
    post = lines.slice(mEnd + 1);
  } else {
    const anchor = freshAnchor(lines);
    pre = lines.slice(0, anchor);
    post = lines.slice(anchor);
  }

  // Trim trailing blanks off pre and leading blanks off post for a stable shape.
  while (pre.length && pre[pre.length - 1].trim() === '') pre.pop();
  while (post.length && post[0].trim() === '') post.shift();

  const out = [];
  if (pre.length) out.push(...pre, '');
  out.push(...block);
  if (post.length) out.push('', ...post);
  return `${out.join('\n').replace(/\n+$/, '')}\n`;
}

/**
 * @param {ReturnType<typeof parseTasks>} parsed
 * @returns {boolean} true when the on-disk board differs from a fresh render.
 */
export function boardIsStale(parsed) {
  const rendered = renderBoard(parsed);
  return rendered !== `${parsed.lines.join('\n').replace(/\n+$/, '')}\n`;
}

/**
 * Normalize a requested state (glyph char or state name) to a glyph.
 * @param {string} state
 * @returns {string} glyph
 */
export function toGlyph(state) {
  if (Object.prototype.hasOwnProperty.call(GLYPH_STATE, state)) return state;
  if (Object.prototype.hasOwnProperty.call(STATE_GLYPH, state)) return STATE_GLYPH[state];
  throw new Error(`invalid state "${state}" (use one of: todo, in-progress, blocked, done, or a glyph)`);
}

/**
 * Set one task's glyph (and optionally its `blocked-by:` note). Pure: returns
 * the new full content. Throws on unknown id.
 * @param {ReturnType<typeof parseTasks>} parsed
 * @param {string} id
 * @param {string} state glyph or state name
 * @param {{ blockedBy?: string }} [opts]
 * @returns {{ content: string, task: Task }}
 */
export function setTaskState(parsed, id, state, opts = {}) {
  const task = parsed.byId.get(id);
  if (!task) throw new Error(`unknown task id: ${id}`);
  const glyph = toGlyph(state);
  const lines = parsed.lines.slice();
  const header = lines[task.headerLine];
  lines[task.headerLine] = header.replace(/^- \[[^\]]*\]/, `- [${glyph}]`);

  if (opts.blockedBy != null) {
    // Update an existing blocked-by metadata line or insert one right after the header.
    const indent = /^(\s+)/.exec(lines[task.headerLine + 1] || '')?.[1] || '   ';
    let updated = false;
    for (let i = task.headerLine + 1; i < lines.length && /^\s+\S/.test(lines[i]); i++) {
      if (/^\s*blocked-by:/.test(lines[i])) {
        lines[i] = `${indent}blocked-by: ${opts.blockedBy}`;
        updated = true;
        break;
      }
    }
    if (!updated) lines.splice(task.headerLine + 1, 0, `${indent}blocked-by: ${opts.blockedBy}`);
  }

  return { content: `${lines.join('\n').replace(/\n+$/, '')}\n`, task };
}

/**
 * Apply many glyph updates in one pass. The mechanical core of a state sync
 * (e.g. mirroring a Beads board back into `tasks.md`): given a map of
 * `{ taskId: glyph|state }`, rewrite each matching header. Pure.
 * @param {ReturnType<typeof parseTasks>} parsed
 * @param {Record<string, string>} statesMap
 * @returns {{ content: string, applied: string[], unknown: string[] }}
 */
export function applyStates(parsed, statesMap) {
  const lines = parsed.lines.slice();
  /** @type {string[]} */
  const applied = [];
  for (const t of parsed.tasks) {
    if (Object.prototype.hasOwnProperty.call(statesMap, t.id)) {
      const glyph = toGlyph(statesMap[t.id]);
      lines[t.headerLine] = lines[t.headerLine].replace(/^- \[[^\]]*\]/, `- [${glyph}]`);
      applied.push(t.id);
    }
  }
  const unknown = Object.keys(statesMap).filter((id) => !parsed.byId.has(id));
  return { content: `${lines.join('\n').replace(/\n+$/, '')}\n`, applied, unknown };
}

/* --------------------------------------------------------------- snapshot */
/**
 * @param {ReturnType<typeof parseTasks>} parsed
 * @returns {Record<string, string>} id -> glyph for every task.
 */
export function glyphsOf(parsed) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const t of parsed.tasks) out[t.id] = t.glyph;
  return out;
}

/**
 * Compare current glyphs against a coordinator-owned snapshot and report tasks
 * newly flipped to `[x]` that the snapshot does not record as done — the
 * "human-applied [x] without evidence" guard.
 * @param {ReturnType<typeof parseTasks>} parsed
 * @param {Record<string, string> | undefined} snapshotGlyphs
 * @returns {{ baseline: boolean, unexpectedDone: string[] }}
 */
export function diffAgainstSnapshot(parsed, snapshotGlyphs) {
  if (!snapshotGlyphs) return { baseline: false, unexpectedDone: [] };
  const unexpectedDone = [];
  for (const t of parsed.tasks) {
    if (t.glyph === 'x' && snapshotGlyphs[t.id] !== 'x') unexpectedDone.push(t.id);
  }
  return { baseline: true, unexpectedDone };
}
