/**
 * Clearline Tailwind preset.
 *
 * Resolve <clearline-root> to the installed skill root before requiring this
 * file. See ../README.md for an import example.
 */
module.exports = {
  theme: {
    extend: {
      colors: {
        cl: {
          blue: '#00A4EF',
          green: '#7FBA00',
          orange: '#FFB900',
          red: '#F25022',
          gray: '#737373',
          bg: '#FFFFFF',
          'bg-subtle': '#F3F2F1',
          'bg-dark': '#1B1A19',
          'bg-subtle-dark': '#2B2A29',
          border: '#E1DFDD',
          'border-dark': '#737373',
          text: '#201F1E',
          'text-muted': '#605E5C',
          'text-muted-dark': '#C8C6C4',
          'text-on-dark': '#FFFFFF',
          'primary-bg': '#0067B8',
          'primary-fg': '#FFFFFF',
          'success-bg': '#107C10',
          'success-fg': '#FFFFFF',
          'warning-bg': '#7A5800',
          'warning-fg': '#FFFFFF',
          'danger-bg': '#A4262C',
          'danger-fg': '#FFFFFF',
          'control-border': '#767676',
          'control-border-on-dark': '#A19F9D',
          link: '#0065B3',
          'link-on-dark': '#75B6E7',
          'focus-ring': '#005A9E',
          'focus-halo': '#FFFFFF',
          'focus-ring-on-dark': '#75B6E7',
          'focus-halo-on-dark': '#1B1A19',
          'docs-code-bg': '#F3F2F1',
          'docs-code-bg-dark': '#404040',
          'docs-tip-bg': '#DFF6DD',
          'docs-tip-border': '#107C10',
          'docs-tip-bg-dark': '#054B16',
          'docs-tip-text-dark': '#DFF6DD',
        },
      },
      fontFamily: {
        'cl-body': [
          'Inter',
          'Inter Variable',
          'system-ui',
          '-apple-system',
          'Helvetica Neue',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        'cl-heading': [
          'Inter',
          'Inter Variable',
          'system-ui',
          '-apple-system',
          'Helvetica Neue',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        'cl-docs': [
          'Inter',
          'Inter Variable',
          'system-ui',
          '-apple-system',
          'Helvetica Neue',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        'cl-mono': [
          'JetBrains Mono',
          'JetBrains Mono NL',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Liberation Mono',
          'DejaVu Sans Mono',
          'monospace',
        ],
      },
      fontWeight: {
        'cl-regular': '400',
        'cl-semibold': '600',
      },
      fontSize: {
        'cl-display': ['48px', { lineHeight: '1.15', fontWeight: '600' }],
        'cl-h1': ['36px', { lineHeight: '1.2', fontWeight: '600' }],
        'cl-h2': ['28px', { lineHeight: '1.25', fontWeight: '600' }],
        'cl-h3': ['22px', { lineHeight: '1.3', fontWeight: '600' }],
        'cl-h4': ['18px', { lineHeight: '1.35', fontWeight: '600' }],
        'cl-body-lg': ['18px', { lineHeight: '1.5' }],
        'cl-body': ['16px', { lineHeight: '1.5' }],
        'cl-caption': ['13px', { lineHeight: '1.4' }],
        'cl-micro': ['11px', { lineHeight: '1.3' }],
        'cl-docs-title': ['40px', { lineHeight: '52px', fontWeight: '600' }],
        'cl-docs-h2': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'cl-docs-h3': ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        'cl-docs-body': ['16px', { lineHeight: '28px' }],
        'cl-docs-compact': ['14px', { lineHeight: '1.5' }],
        'cl-docs-code': ['14px', { lineHeight: '19px' }],
      },
      maxWidth: {
        'cl-docs-page': '1280px',
        'cl-docs': '1200px',
        'cl-docs-figure': '1200px',
        'cl-docs-wide': '1064px',
        'cl-docs-readable': '928px',
      },
      spacing: {
        'cl-0': '0px',
        'cl-1': '4px',
        'cl-2': '8px',
        'cl-3': '12px',
        'cl-4': '16px',
        'cl-5': '24px',
        'cl-6': '32px',
        'cl-7': '48px',
        'cl-8': '64px',
        'cl-mark-size-compact': '16px',
        'cl-mark-size-default': '24px',
        'cl-mark-size-hero': '40px',
        'cl-mark-clear-space-compact': '16px',
        'cl-mark-clear-space-default': '24px',
        'cl-mark-clear-space-hero': '40px',
      },
      height: {
        'cl-control-compact': '32px',
        'cl-control-default': '40px',
        'cl-control-touch': '48px',
      },
      minWidth: {
        'cl-card': '240px',
      },
      borderRadius: {
        'cl-sm': '2px',
        'cl-md': '4px',
        'cl-lg': '8px',
        'cl-pill': '9999px',
      },
      borderWidth: {
        'cl-control': '1px',
      },
      outlineWidth: {
        'cl-focus': '2px',
      },
      outlineOffset: {
        'cl-focus': '2px',
      },
      boxShadow: {
        'cl-1': '0 1px 2px rgba(0, 0, 0, 0.08)',
        'cl-2': '0 2px 6px rgba(0, 0, 0, 0.10)',
        'cl-3': '0 4px 12px rgba(0, 0, 0, 0.12)',
      },
      transitionDuration: {
        'cl-none': '0ms',
        'cl-reduced': '1ms',
        'cl-micro': '150ms',
        'cl-standard': '250ms',
        'cl-entrance': '400ms',
      },
      transitionTimingFunction: {
        'cl-enter': 'cubic-bezier(0.1, 0.9, 0.2, 1)',
        'cl-exit': 'cubic-bezier(0, 0, 0.2, 1)',
      },
    },
  },
};
